### ISSUE TITLE
Portable version, can't change drive

### ISSUE THREAD

**Issue by lordmax** [pbek/QOwnNotes#1183]
Hi I'm experiencing a problem with the portable version

If I change the note folder path from disk F (where is the program) to C (where I want to save the notes) it don't work anymore.

As you can see in the image the path aren't correct

**Comment by lordmax** [comment]
Sorry, I have problems with images
![Portable_error](https://user-images.githubusercontent.com/349971/56149164-3b92c980-5fac-11e9-8ae6-09fe55555f5c.jpg)

**Comment by pbek** [comment]
I'm sorry, Windows can't handle a relative path to a different drive. You can only use the portable mode on the same drive. (that was the reason for having a portable mode in the first place) is there a reason for you to use the portable mode?

**Comment by lordmax** [comment]
Yes

I dont' want to install anything of not absolutely necessary on my pc.
I use every software I can as a portable app (and appimage on linux too)

But, for working reason, I have dropbox installed and is on drive C but all my portable apps are on drive F
It's a problem for me.
There's some .ini settings I can try to resolve?

Thanks

**Comment by pbek** [comment]
> I dont' want to install anything of not absolutely necessary on my pc.

there is no installation process for QOwnNotes, you just run it. the only difference in portable mode is that the settings will not be written to the registry and folders will not be treated as absolute path, but as relative path so that you can carry your folder with QOwnNotes, settings and notes with you

> But, for working reason, I have dropbox installed and is on drive C but all my portable apps are on drive F

you could try mapping folders: https://superuser.com/questions/620740/how-to-mount-a-folder-to-folder-in-windows-7
>

https://superuser.com/questions/620740/how-to-mount-a-folder-to-folder-in-windows-7
