### ISSUE TITLE
OS X: App doesn't work, need to manually select a default file extension to fix

### ISSUE THREAD

**Issue by Commenter123** [pbek/QOwnNotes#123]
Hi,

I just installed the app and tried to create a new note called `newnote`:
This app tjem created a new file `newnote.` (notice the period at the end, but no file extension) in the notes folder. But the new note didn't appear in this app's sidebar.

I checked the settings and found an option (under "General"): "Default file extension". No entry was selected.
I selected one of the entries and since then everything works perfectly. New notes are now called `newnote.md` and also appear in the sidebar

So please select one file extension by default.

**Comment by pbek** [comment]
Thank you for the report and sorry for the late reply. I didn't get any notification about your post. :(

As a matter of fact I found out about this behavior myself two days ago and fixed it. :)
https://github.com/pbek/QOwnNotes/commit/abc2162abb0f1e6f74c95f5441f6cbc4649dafa2

Will be fixed in version 1.3.3.

**Comment by pbek** [comment]
1.3.3 is now released... Since you will not easily be able to test if it works I will just close this issue for now. Thanks again for the report!
