### ISSUE TITLE
Operating system shutdown process interrupted

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1269]
Now and then it seems QOwnNotes is able to interrupt the shutdown process of the operating system.
May be related with starting a `git commit` when the application quits.

**Comment by pbek** [comment]
## 19.8.7
- attempted to fix an occasional operating system shutdown process interruption

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by barkingbandicoot** [comment]
I updated to the new version.
Bug is still present.

1.Choose shutdown
2. All app close.
3. Receive notification that QownNotes has stopped shutdown.
4. Open menu. Open QownNotes. Close QownNotes.
5. Choose shutdown. Computer shuts down.

Kubuntu 19.04 on Dell Precision 5520 & 5720.

**Comment by pbek** [comment]
Could you please post the output from your debug settings (see issue template) so that I can compare our settings and other stats.

**Comment by bipox** [comment]
Hi and thank you for this great program. I use it daily and love it!

I'm running Kubuntu 19.04 and KDE Neon.

After shutdown gets interrupted, nothing new appears in the log.

**Comment by pbek** [comment]
Thank you for your kind words, @bipox. Do you have debug message turned on in the log? What happens in the log before the shutdown occurs?

And could you please post the output from the debug settings.

**Comment by bipox** [comment]
Yes I have debug message turned on, no new message appears after the shutdown fails.

Output in attachment

[QOwnNotes Debug Information.txt](https://github.com/pbek/QOwnNotes/files/3538608/QOwnNotes.Debug.Information.txt)

**Comment by pbek** [comment]
## 19.10.4
- attempted to fix occasional desktop environment session logout interruptions

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by bipox** [comment]
I tried this a few times: 

- if QOwnNotes has an open window, trying to shut down through GUI will close QOwnNotes' window and will show the "shutdown inhibited" popup. 
If I try again, the computer now shuts down

- if QownNotes is running in the back with no open window, nothing prevents the computer from shutting down

This is already much better

**Comment by pbek** [comment]
I now shut down the app as soon it gets the event to "store its data". I don't know if it can get better than that... :)

**Comment by bipox** [comment]
Already miles better, thanks!

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by mickenorlen** [comment]
Have the same issue. Seems to only happen when window is open (for me usually on another workspace).

#### Expected behaviour

When trying to end session in KDE eg: logout, shudown, reboot. It should happen on first try.

#### Actual behaviour

The first time i try to end session, QOwnNotes application quits but then logout is cancelled with notification `Logout canceled by '/usr/bin/QOwnNotes' `.

The second try works

#### Steps to reproduce

Logout or reboot

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `fre jan. 28 18:20:22 2022`
**Version**: `22.1.4`
**Build date**: `Jan  7 2022`
**Build number**: `935`
**Platform**: `linux`
**Operating System**: `Arch Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/micke/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/micke/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 960x540`
**Icon theme**: `breeze-dark`
**Notes in current note folder**: `18`
**Calendar items**: `1`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://cloud.orbcoding.com`
**appIsValid**: `no`
**notesPathExists**: `unknown`
**connectionErrorMessage**: `The specified configuration cannot be used.`

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`
**Language codes**: `en_US, en_US-large, it_CH, it_IT, sv_FI, sv_SE`
**Language names**: `American English (United States), American English (United States) [large], italiano (Svizzera), italiano (Italia), svenska (Finland), svenska (Sverige)`
**Application dictionaries path**: `/home/micke/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/micke/Nextcloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `barcoteatro`
**database file**: `/home/micke/Nextcloud/Notes/notes.sqlite`

## Cloud connections

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: `https://cloud.orbcoding.com`
**username**: `mickenorlen`
**accountId**: `mickenorlen`

## Enabled scripts

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `30`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `true`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `2`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/showLineNumbers** (QString): `true`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath** (QString): `/home/micke/Nextcloud/Documents`
**FileDialog/LastPath-SettingsExport** (QString): `/home/micke/Nextcloud/Documents`
**GlobalShortcuts/MainWindow-actionShow_Hide_application** (QString): `Meta+N`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2022-01-28T18:11:08.307`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `Dev`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Hack,10,-1,7,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,0,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/readonly-mode-allow** (QString): `16384`
**NoteFolder-1/NoteTabNameList** (QStringList): `Sticky, Sticky`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): 
```
Home, Dev
barcoteatro
```
**NoteFolder-1/allowDifferentNoteFileName** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 53 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `52`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**Shortcuts/MainWindow-actionFind_action** (QString): `Ctrl+Shift+P`
**Shortcuts/MainWindow-actionShow_Todo_List** (QString): `Meta+T`
**Shortcuts/MainWindow-action_Print_note_markdown** (QString): *empty*
**Shortcuts/MainWindow-togglePanel-notePreviewDockWidget** (QString): `F3`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TodoDialog/geometry** (QByteArray): `<binary data>`
**TodoDialog/mainSplitterState** (QByteArray): `<binary data>`
**TodoDialog/showCompletedItems** (QString): `2`
**TodoDialog/showDueTodayItemsOnly** (QString): `0`
**TodoDialog/todoListSelectorSelectedItem** (QString): `Home`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (QString): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**interfaceStyle** (QString): `Breeze`
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/micke/Nextcloud/Notes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `true`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): `Home, Dev`
**ownCloud/todoCalendarEnabledList** (QStringList): `Home, Dev`
**ownCloud/todoCalendarEnabledUrlList** (QStringList): `https://cloud.orbcoding.com/remote.php/dav/calendars/mickenorlen/home-1/, https://cloud.orbcoding.com/remote.php/dav/calendars/mickenorlen/dev-2/`
**ownCloud/todoCalendarUrlList** (QStringList): `https://cloud.orbcoding.com/remote.php/dav/calendars/mickenorlen/home-1/, https://cloud.orbcoding.com/remote.php/dav/calendars/mickenorlen/dev-2/`
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): `The specified configuration cannot be used.`
**ownCloudInfo/notesPathExistsText** (QString): `unknown`
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2022-01-26T14.36.19, Note 2022-01-26T13.55.22, Note 2022-01-26T13.43.10, Note 2022-01-25T10.24.33, Note 2022-01-23T09.37.37, Note 2022-01-23T09.31.21, Note 2022-01-19T18.33.18, Note 2022-01-19T16.19.23, Note 2022-01-19T16.19.08, Note 2022-01-19T16.01.03, Note 2022-01-17T23.36.58, Note 2022-01-17T20.14.04, Note 2022-01-17T17.31.11, Note 2022-01-16T16.42.16, Note 2022-01-16T00.59.27, Note 2022-01-14T13.14.54, Note 2022-01-12T19.45.35, Sticky`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `true`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**SHELL**: `/bin/zsh`
**SESSION_MANAGER**: `local/arch:@/tmp/.ICE-unix/601,unix/arch:/tmp/.ICE-unix/601`
**QT_SCREEN_SCALE_FACTORS**: `eDP1=2;DP1=2;DP2=2;HDMI1=2;HDMI2=2;VIRTUAL1=2;`
**XDG_CONFIG_DIRS**: `/home/micke/.config/kdedefaults:/etc/xdg`
**GDK_DPI_SCALE**: `0.5`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**DOTNET_ROOT**: `/usr/share/dotnet`
**SSH_AUTH_SOCK**: `"$XDG_RUNTIME_DIR/ssh-agent.socket"`
**DESKTOP_SESSION**: `plasma`
**LC_MONETARY**: `sv_SE.UTF-8`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/micke/.gtkrc:/home/micke/.config/gtkrc`
**XCURSOR_SIZE**: `24`
**GTK_MODULES**: `canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/micke`
**LOGNAME**: `micke`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_TYPE**: `x11`
**SYSTEMD_EXEC_PID**: `501`
**_**: `/usr/bin/QOwnNotes`
**XAUTHORITY**: `/home/micke/.Xauthority`
**MOTD_SHOWN**: `pam`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/micke/.gtkrc-2.0:/home/micke/.config/gtkrc-2.0`
**HOME**: `/home/micke`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**DOTNET_BUNDLE_EXTRACT_BASE_DIR**: `/home/micke/.cache/dotnet_bundle_extract`
**KDE_SESSION_UID**: `1000`
**XDG_SESSION_CLASS**: `user`
**USER**: `micke`
**KDE_SESSION_VERSION**: `5`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**DISPLAY**: `:0`
**SHLVL**: `0`
**MOZ_ENABLE_WAYLAND**: `1`
**LC_MEASUREMENT**: `sv_SE.UTF-8`
**XDG_VTNR**: `2`
**XDG_SESSION_ID**: `1`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**LC_TIME**: `sv_SE.UTF-8`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**LC_COLLATE**: `sv_SE.UTF-8`
**XCURSOR_THEME**: `breeze_cursors`
**GTK3_MODULES**: `xapp-gtk3-module`
**KDE_FULL_SESSION**: `true`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/home/micke/.dotnet/tools:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**GDK_SCALE**: `2`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**KDE_APPLICATIONS_AS_SCOPE**: `1`
**MAIL**: `/var/spool/mail/micke`
**LC_NUMERIC**: `sv_SE.UTF-8`
**OLDPWD**: `/home/micke`
</details>

**Comment by pbek** [comment]
Do you also have the issue if you disable the system tray icon?

**Comment by mickenorlen** [comment]
No that fixed it! Thanks a lot
