### ISSUE TITLE
[F] Move note to SubFolder of another notebook

### ISSUE THREAD

**Issue by truthsword** [pbek/QOwnNotes#1294]
#### Expected behavior

I need the capability to move the note (in one move) from Notebook A to a subfolder in Notebook B.
Thank you.

#### Actual behavior

Presently the right-click "Move notes to ..." permits a note to be relocated to another notebook.

#### Steps to reproduce

Right-click note

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Wed Sep 18 12:45:21 2019`
**Version**: `19.9.14`
**Build date**: `Sep 18 2019`
**Build number**: `4573`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.0`
**Qt Version (runtime)**: `5.13.0`
**Portable mode**: `no`
</details>

**Comment by pbek** [comment]
Although QOwnNotes has no concept of the sub-folders of another note folder I don't drop this FR yet, maybe I do it anyway some day.

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by truthsword** [comment]
Very nice. Thank you!

**Comment by pbek** [comment]
Yes, as I was saying, QOwnNotes has no concept of a "note" or media-folders in some "random folder" that is not a loaded note-folder.
I just remembered that I wrote something that is copying media files to a "media" folder in the destination path back then when a note is copied/moved. But that will only work with the legacy media-links and only with the note folder root (and not in a sub-folder).
In fact I even have to remove that for sub-folders somehow because subfolders have no media folder...

https://github.com/pbek/QOwnNotes/blob/4ef821c876817d1596ae99a0b3f5cfc4fb4b218c/src/entities/note.cpp#L315-L374

**Comment by truthsword** [comment]
I understand. I added media folders to my subfolders thinking that would be a workaround. 

Still, I must say your app here is quite amazing. Since the majority of my notes don't have graphic attachments, this most recent feature saves me much time.

Now I have to catch up on the changes you made in the past 2 weeks, and see how I might use those in my day-to-day routine. Thank you.

**Comment by pbek** [comment]
Thank you. :smile:  And yes, a lot has happened in the past weeks. 16 releases this month weren't for nothing. :smile_cat:

**Comment by pbek** [comment]
A lot of effort went into #266 and the image, attachment and link dialogs.
