### ISSUE TITLE
feature request: Stylus support

### ISSUE THREAD

**Issue by manscrober** [pbek/QOwnNotes#1312]
it would be nice to include a little drawing without much hassle, or draw lines between words.

I'm looking for something similar to onenote with a more structured layout.
For saving it, Maybe it would be possible to include svg in the text file, or even just a normal image that is created and resized dynamically with stylus/mouse input.

Maybe it's possible to use existing open source code like the QT scribblearea example and adapt it

**Comment by pbek** [comment]
> it would be nice to include a little drawing without much hassle, or draw lines between words.

The text editor in QOwnNotes is plaintext only (the basis is a QPlainTextEdit) so you cannot draw anything into it.

But you could check the script https://github.com/qownnotes/scripts/tree/master/scribble in the script repository. That could fit your need.

**Comment by besswein** [comment]
The script looks like a good solution for now, but in the long term it could be interesting to be able to embed other editing methods / editors just like you can include OLE-Objects in LibreOffice text documents. (doesn't need to be OLE-Objects)

This might be a way to solve several more advanced feature requests (that otherwise would be out of context of the application) at once by just using other existing applications that are more specialized to the specific task.

Note: I'm not really into the topic and this is just a quick thought, so don't bother if this is too complex to realice

**Comment by pbek** [comment]
> The script looks like a good solution for now, but in the long term it could be interesting to be able to embed other editing methods / editors just like you can include OLE-Objects in LibreOffice text documents. (doesn't need to be OLE-Objects)

Are you aware that simple markdown text files are used in QOwnNotes? :smile: *Text files* as in *human readable text files*.

**Comment by besswein** [comment]
Well my example was a little bit over the top, but it was the first thing that came in my mind to discribe what I ment.

What I thought of, then I was writing my previous comment, is when we're linking to a file and open an external application to edit it (actualy what the script does), we're alredy doing something vary similar to what they do: linking to an object which is edited and interpreted in an other way then the main document.
So maybe there is a way to include an editor directly into the application, which would be way more intuitive then the script.
(don't know if something like that could even be generalised, cause again im not into the topic)

Background:
I like markdown for taking notes because its simple text files, but sometimes I've got the need of adding a quick sketch to illustrate.
And since there's a growing number of convertibles, stylus support is somthing which could make this app stand out of others.

**Comment by pbek** [comment]
Why would you like to add a rudimentary paint dialog, that no one would like if you can have an external solution easily with above script?

**Comment by besswein** [comment]
That's actually an argument but unfortunately I can't experiment with the script to see how intuitiv it is cause it seems to be broken see [my issue](https://github.com/qownnotes/scripts/issues/71)

**Comment by pbek** [comment]
I will close this issue until there is more information.
