### ISSUE TITLE
Source code as versioned tarball

### ISSUE THREAD

**Issue by noldensystemelektronik** [pbek/QOwnNotes#133]
Hi,
is it possible to have the sourcecode of QOwnNotes as a versioned tarball for download ? That way FreeBSD could have a port as well based on the source distribution.

Thanks!

**Comment by pbek** [comment]
I'd love to do that with GitHub, but it uses the `git archive` command and because of this the source code of git sub-modules is not included in the archives. What is the FreeBSD way to distribute software? Maybe I can build something like I do for AUR or the Gentoo overlay.

**Comment by noldensystemelektronik** [comment]
You just need to provide a tarball containing all the sources named qownnotes-1.3.6.tar.gz that extracts to a source directory qownnotes-1.3.6. That would help all who want to build the program from source (like debian and other distributions) to include your program pre-compiled and as source package (to rebuild the program) in all Linux distros and also BSD unix (FreeBSD, NetBSD, OpenBSD and others). You can have a look at other software such as Qt itself where you can get the sources as tarballs. Other than on Windows you seldom have the need to provide precompiled packages on Linux or Unix because of all the different distros.

**Comment by pbek** [comment]
I was hoping that GitHub will support archives with all submobiles some day, so that I don't have to bother creating a source distribution that I have to host somewhere myself.

Meanwhile I created packages (and also source packages) for a lot of distributions (often tailored a bit to the distribution).
<http://www.qownnotes.org/installation>

If I find an easy (scriptable) way to host source tar-balls, ideally not on my own hardware, I will start to create source packages. Do you have any suggestions?

Meanwhile you can always do:
<http://www.qownnotes.org/installation#building>

**Comment by pbek** [comment]
Good news, @noldensystemelektronik...
I setup a script for distributing source archives to SourceForge that I will call in my build process.

Files will be uploaded to:
<https://sourceforge.net/projects/qownnotes/files/src/>

Files will be accessible like that:
<http://downloads.sourceforge.net/project/qownnotes/src/qownnotes-16.05.2.tar.xz>

**Comment by pbek** [comment]
If you can, please tell me if you were able to build from these archives.
