### ISSUE TITLE
Dark mode kde

### ISSUE THREAD

**Issue by bijang** [pbek/QOwnNotes#1352]
Please could look at the application on linux (kde in my case). Dark colour theme, the icons dont play well with it

**Comment by pbek** [comment]
What do you mean by "don't look well". By default the icons from your free desktop icon set are used. 

Can you please post the output from the debug settings (see issue template).
And can you please supply a screenshot.

**Comment by Waqar144** [comment]
@pbek
I think he means, if the default KDE theme is set to dark, on the first run QON looks like this:

![image](https://user-images.githubusercontent.com/7696024/68082296-afa79880-fe3c-11e9-8f3d-153a7a880376.png)

because QON is using the **light theme**, hence the dark icons.

@bijang 
To fix this, go to Menu.
1. Open Note->Settings.
2. On the left hand side click **Interface**
3. On the right hand side, check **Enable dark mode icon theme** or if you want to use the system icon theme, check **Enforce System Icon theme**

**Comment by pbek** [comment]
It should use the icon theme from KDE by default, so if breeze dark is used by KDE it should be ok too...

**Comment by Waqar144** [comment]
> It should use the icon theme from KDE by default, so if breeze dark is used by KDE it should be ok too...

But what if the desktop icon theme is not breeze?

**Comment by bijang** [comment]
Thank you, apologies for the vagaries initially, you got the idea though and the fix, thank you. Yes Breeze dark wasn't working for some reason, thanks Waqar for pointing out the manual fix
