### ISSUE TITLE
Cannot search all subfolders at once

### ISSUE THREAD

**Issue by dorearendil** [pbek/QOwnNotes#1470]
Hi,
I love QOwnNotes, which I use everyday for pretty much every area in my life. Great software!
One thing bugs me though: for some reason, I cannot search through all the subfolders, even when using the keyboard shortcut shown [here](https://www.qownnotes.org/shortcuts/QOwnNotes): Alt+F does the same thing as if I click in the searchbar directly (i.e. it only searches for the keyword in the current subfolder). Has anyone else encountered this issue?
I'm using Ubuntu 18.04.3 LTS.

**Comment by pbek** [comment]
If you want to show all notes in a sub-folder including its child-folders there is a checkbox in the *Panel settings*.

**Comment by pbek** [comment]
> I love QOwnNotes, which I use everyday for pretty much every area in my life. Great software!

Thank you for your kind words!

**Comment by dorearendil** [comment]
Thanks Patrizio. However, my question is left unanswered - i.e.: how can I search for a note in all QOwnnotes folders at once, using a keyword?
(perhaps I should have used the word "folder" instead of "subfolder" in my question, sorry)

**Comment by Waqar144** [comment]
> how can I search for a note in all QOwnnotes folders at once, using a keyword?

1. Open settings (Shortcut: <kbd>Ctrl</kbd> + <kbd>,</kbd>)
2. On the left side, select **Note folders**
3. On the right side, - check **Use note sub-folders**
4. Then again, on the left side select **Panels**
5. On the right side, check **Show all notes of a folder including their subfolders**
6. On the right side, check **Display note subfolders as full tree**
7. (Optional) check **Show the number of matches in each note**

The last option is good when you want to search for something *inside* multiple notes. Otherwise the search is only limited to the note file names.

To actually do the search,
1. Select the folder you want. If you want to search in all folders, select your root folder.
2. Do the search in the panel below (Note list panel)

If **Note list panel** is not visible, you can make it visible by going to the menu, **Window** -> **Panels** -> Show note list panel

Hope that helps

**Comment by pbek** [comment]
@Waqar144 he is talking about note folders, not sub-folders 😬 

> Thanks Patrizio. However, my question is left unanswered - i.e.: how can I search for a note in all QOwnnotes folders at once, using a keyword?

no, that isn't possible, not folders are (and should be) completely separated

**Comment by Waqar144** [comment]
Note folders and subfolders are so easy to mix :grin:

**Comment by dorearendil** [comment]
Thanks @Waqar144 and @pbek for your replies.

> no, that isn't possible, not folders are (and should be) completely separated
While I can understand that it may be important to keep the note folders separated from a technical perspective, from a user-experience standpoint it's a shame not to be able to search through different folders at once... In my case, I have 22 separate folders (23 including "default"), and it sometimes happens that I drag-drop a note into the wrong folder for example. Finding that note, days or weeks later, can be very troublesome, and require me to open another search software - using the current search function, I have to go through each of the 22 folders one after the other!
Would it be possible to make this a future improvement of QOwnNotes?

**Comment by pbek** [comment]
Everything is "possible" given enough time and an impetus to do so. But it's not very probable. There are many reasons to keep them separated. For example you can use different large note folders and also smaller without losing a lot of memory... If you need more folders at the same time use note sub-folders.

**Comment by dorearendil** [comment]
OK understood, thanks Patrizio. I'll try to experiment with subfolders then.
Thanks for your work on QON!

**Comment by pbek** [comment]
Thank you for your kind words and happy foldering. :grin:
