### ISSUE TITLE
Korean last character input problem

### ISSUE THREAD

**Issue by Anongh** [pbek/QOwnNotes#1495]
1. Type "한국어"
2. Click anywhere
3. "어" disappears from "한국어" and only "한국" remains.
4. Trying to enter another word, '안녕하세요', for example
5. The sudden disappearance of "어" will appear at the head of the "안녕하세요" word.
6. So the result is "어안녕하세요"

Perhaps "어" disappears only on the screen and it exists in the memory buffer.

I assume that the same problem will occur in Chinese or Japanese, but I don't have the IME of those languages, so I don't know if they are also problematic.

My OS  is Windows 8.1 and I'm using the latest version of QON.

Thanks for creating a great app.

**Comment by pbek** [comment]
I could not reproduce that issue on KDE Neon.

![image](https://user-images.githubusercontent.com/1798101/70419268-65ca5780-1a65-11ea-8a25-96ade0a4e682.png)

There character "어" is still there after I clicked in an other line.

**Comment by pbek** [comment]
> Thanks for creating a great app.

Thank you for your kind words. :smile:

**Comment by Waqar144** [comment]
Cannot reproduce it either. Maybe it only happens when you type and not copy paste :thinking:

**Comment by Anongh** [comment]
I just have installed and tested QON on Windows 10 on another computer and the same problem occurs.

@Waqar144 Hi, do you use Windows too?

![test hangul](https://user-images.githubusercontent.com/22952514/70435780-1585e080-1acb-11ea-9271-eca001d6f4f2.gif)

**Comment by pbek** [comment]
> and the same problem occurs

I never heard of any issues for Japanese or Chinese.
Do you also have this problem when pasting the text?

> do you use Windows too?

no, I don't think he is :grin:

**Comment by Anongh** [comment]
There is no problem with putting a text. :relieved:

**Comment by Waqar144** [comment]
I am on Linux.

It's going to be hard to reproduce, as I don't have any idea how to  write Korean🤔😅

**Comment by Anongh** [comment]
You don’t have to suffer like that.:smile:

In many cases, I type the text and press the enter key, which is not a big problem, and it can be easily solved by typing the space in the last word.
I am glad that there is no problem with other Asian characters.

**Comment by Waqar144** [comment]
> You don’t have to suffer like that.smile
> 
> In many cases, I type the text and press the enter key, which is not a big problem, and it can be easily solved by typing the space in the last word.
> I am glad that there is no problem with other Asian characters.

Text input handling is usually handled by Qt(the framework/library) we are using. I am guessing this is a problem on their side. When did you start seeing this issue?

We are working hard to keep everything running well all the time. Thanks :heart:

**Comment by Anongh** [comment]
I've been through the issue since I set up the editor.

> We are working hard to keep everything running well all the time. Thanks heart

That's why this editor is the best. :thumbsup:

**Comment by Waqar144** [comment]
Honestly this should never happen. If it doesn't happen when pasting text, it shouldn't while typing either.

**Comment by page-down** [comment]
This is because the last word was not fully confirmed, and QT's support for Microsoft Windows Text Services Framework and the input method's handling of unconfirmed characters eventually caused this problem.

To clarify, I don’t know how to enter Korean. The following are just some attempts to reproduce the problem.

Here is my reproduction of the problem screen recording:

- Windows 10.0.17763 1809
- Korean Microsoft IME
- QOwnNotes 19.12.14

(1) Korean + QOwnNotes
![kr-qownnotes](https://user-images.githubusercontent.com/57713011/71318719-c333bf00-24cf-11ea-9e47-a7b5078df2f2.gif)
한국아 `gksrnrdj`
- gks = 한 (Finally confirmed)
- rnr = 국 (Finally confirmed)
- dj = 어 (Pre-output, to be confirmed)

Korean Microsoft IME default handling of unconfirmed characters:
Output predicted characters at the current cursor.

(2) Chinese + QOwnNotes
![zh-qownnotes](https://user-images.githubusercontent.com/57713011/71318808-ddba6800-24d0-11ea-9151-0382702959c1.gif)

Chinese IME default handling of unconfirmed characters:
For unconfirmed characters, clear the prediction.

Therefore, under normal use, Chinese input in QT will not be a big problem.

(3) Korean + Notepad
![kr-notepad](https://user-images.githubusercontent.com/57713011/71318956-c1b7c600-24d2-11ea-890e-40e781b4646b.gif)

In this screencast, it can be clearly seen that the last character has not been finalized.

However, Notepad's approach to this seems to be that the input method outputs unconfirmed characters at the current cursor, and Notepad moves the cursor to another position.

(4) Chinese + Notepad
![zh-notepad](https://user-images.githubusercontent.com/57713011/71318871-9aacc480-24d1-11ea-847b-42930cf0976a.gif)
In this screencast, Microsoft's Notepad works well with advanced Chinese input methods using the TSF framework.

Unfinalized characters will move with the pointer and will not be output.
