### ISSUE TITLE
Feature Request: Reminder

### ISSUE THREAD

**Issue by dasmaetthes** [pbek/QOwnNotes#151]
Reminder - Write down the date and time when you want the note to be automatically opened.

**Comment by pbek** [comment]
Thank you for your suggestions. Could you please open different feature requests for each of them, because they have nothing to do with each other. 
1) kind of works if you are using ownCloud (todo list), I don't see the value without the possibility that you get reminded my a smartphone too...
2) sounds interesting :)
3) yeah, that's a good idea, I already had something like that in mind

**Comment by pbek** [comment]
Like I said, there already is a reminder functionality with tasks. I can't see any use case adding an other.

**Comment by dasmaetthes** [comment]
Yes, you're right about that. Wouldn't be that useful than.

**Comment by pbek** [comment]
Ok, I'll close that one. Reminders make much more sense if they get synced to devices that are always on (and that already works with QOwnNotes).
