### ISSUE TITLE
Cannot remove just third quote in a line with three quotes

### ISSUE THREAD

**Issue by pbek** [pbek/QOwnNotes#1629]
@Waqar144, maybe something for you. 😁 

#### Expected behaviour

I want to remove the 3rd `"` from `test "test""`.

#### Actual behaviour

The 2nd and 3rd `"` get removed.

#### Steps to reproduce

- paste `test "test""` in a note in a new line
- try to remove just the third `"` with backspace
- the 2nd and 3rd `"` get removed

#### Relevant log output in the Log panel
<details><summary>Expand</summary>

## General Info

**Version**: `20.2.4`
**Build date**: `Feb 13 2020`
**Build number**: `5343`
**Platform**: `macosx`
**Operating System**: `macOS Mojave (10.14)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
</details>

**Comment by Waqar144** [comment]
> I want to remove the 3rd `"`from `test "test"""`.

If you remove the 3rd it probably removes the 4th one alongwith it, right?
If you remove the 4th, it looks backward (since it can't find a matching pair in front) and so 3rd and 4th get removed.

The problem with these is that the closing and opening mark is same so we have no direct way of finding whether a mark is a 'closer' or an 'opener'. Of course we can collect all the marks and analyze them for opener/closer property. And then remove the pair accordingly. For this we would need a rule set (to determine when a mark is a closer and when it is an opener). This is what is happening in the background for em/strong highlighting.

Current implementation is hacky, and it can be problematic in some cases. Consider for example:

```markdown
*italic* some more *text
```

Try and remove the asterisk before **text**.
Result would look like:
```markdown
*italic some more text
```

**Comment by pbek** [comment]
Sorry, my first example had one `"` too much, I edited it now. In my example there is no 4th `"`.

**Comment by pbek** [comment]
My issue was that I somehow managed to only type a single `"` and then when I wanted to to close the brackets I got two more `"` and wasn't able to remove one of them without removing the 2nd one too when using Backspace on the mac (there is no *Delete*).

**Comment by pbek** [comment]
Is there a way to fix that, @Waqar144?

**Comment by Waqar144** [comment]
Yes,
Have a ruleset according to which these will be removed. That's the correct solution.

For now even if I disable the look-back-and-remove-if-no-matching-char-found-in-front it will still cause problems

Consider:

```
*word* and another *word*
```
If you removed the second, it will remove the third one with it, not the first as you might expect.

The rule set for each of these chars is different. For single/double quote it will be simple to find if the char is closer/opener. For * its a bit more complicated. For backtick it's also a little complicated.

**Comment by pbek** [comment]
Removing the 3rd `"` in `test "test""` works correctly with the `Delete` key, but it doesn't with the `Backspace` key. That's all that this issue is about. :grin:

**Comment by Waqar144** [comment]
Should be closed.

backtick ` ` ` is now producing the same issue and is quite frustrating. Will have to fix that as well.
