### ISSUE TITLE
export note as markdown file suggestion

### ISSUE THREAD

**Issue by visualwind** [pbek/QOwnNotes#1634]
When export note as markdown file, the pictiures will lost.
Can you save the picture files to the .pics folder in the same folders of the md file?

**Comment by Waqar144** [comment]
What do you mean by "pictures lost"?

And also, were the pictures from internet or from local file system?

**Comment by pbek** [comment]
Currently that "export" mainly serves as "copy dialog" for people who are not able to copy the markdown file in a file browser.

You cannot "integrate" images (in any sane way) in a markdown file, like we do for the html export. And images can come from all kinds of places in a note. Absolute paths, relative paths, remotely from the internet, ... the same with attachments.

To make that really useful it must gather all external resources of the note, store them to a folder that doesn't exist yet (so that nothing gets overwritten) and rewrite all links to external resources in the note.

But then links to other notes or files also doesn't work...

**Comment by siran** [comment]
I think the OP is looking to export to a new folder a .md note and local images/attachments as a stand-alone folder containing any images/attachments and the .md

optionally also copy the linked .md notes into the same folder

currently something similar is possible when exporting as an HTML

**Comment by pbek** [comment]
> currently something similar is possible when exporting as an HTML

Like I said above, you cannot "integrate" images (in any sane way) in a markdown file, like we do for the html export.

**Comment by pbek** [comment]
## 21.11.4
- you can now choose to also **export attached media files and attachments of a note**
  when **exporting a note as Markdown file**
    - the media files and attachments used in the note will be copied to the
      folder where the note is exported to
    - this only works for files from the media and attachments folder of the note folder
    - the links in the exported Markdown file will be updated

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by siran** [comment]
Works liks a charm! Amazing. Thank you so much for this update!

**Comment by pbek** [comment]
Great, thank you for testing! 😉
