### ISSUE TITLE
Telemetry should be strictly opt-in

### ISSUE THREAD

**Issue by simeonmiteff** [pbek/QOwnNotes#1710]
#### Expected behaviour

Upon first run, QOwnNotes should prompt the user to enable telemetry if desired, and leave it disabled if not explicitly allowed by the user.

#### Actual behaviour

Default settings enable telemetry.

**Comment by pbek** [comment]
Yes, from your perspective that would maybe be nice and is easy to say, but I guess this means that maybe 5% or less of the users would only enable it (simply because most of the uses don't care whether such metrics exist or not and wouldn't bother to go and turn them on in the settings) and that would mean that there is hardly no feedback to base decisions on.

**Comment by pbek** [comment]
I guess the current stance of the internet is "all web-applications or web-based desktop-applications collect a lot of user data" and "desktop applications (newer ones) or Linux operating systems tend to go default-off when they are at a certain user base". if they are too popular and have a large community (and more than 0.1% of the user base starts to complain about default-on), there are other ways to base decisions on. QOwnNotes is far away from that user-base...

**Comment by pbek** [comment]
I personally turn on all metric in the free open source software that I use. It's only a small token to repay all the work people put into it pro bono and an easy way to help to improve the software.

**Comment by simeonmiteff** [comment]
Hi @pbek

Firstly, thanks for QOwnNotes - it is a small island of sanity in the sea of bloated Electron garbage. I love the open and cross-platform approach you've taken.

Also, thanks for your responses. I know this is slightly contentious, so I just want to state up front that I respect that you have (very likely entirely benign) reasons for your position on tracking.

Here are some of my own thoughts for your consideration:

- I think you're right, default-off would cause tracking code to be almost entirely pointless.
- It would be interesting to see if prompting users to opt in on first run (e.g., without a pre-existing config on disk) results in a bigger population opting in (and if so, whether that sample meets your needs).
- Speaking for myself, an opt-in dialog would make me feel better about opting in - I would view it as "acting in good faith" (if I am given a choice, I would more likely trust that tracking data is not abused).
- I also agree that right now most users don't care, but they should, and privacy is a growing concern even for non-technical users. I think in the long term people will begin to value control and safe/conservative defaults as a fundamental indicator of software quality (one that I'm already willing to pay for).

Regards,
Simeon.

**Comment by pbek** [comment]
Thank you for your kind words.

> It would be interesting to see if prompting users to opt in on first run (e.g., without a pre-existing config on disk) results in a bigger population opting in (and if so, whether that sample meets your needs).

Not that I'm aware of (watching other bigger players in the FLOSS world)... People usually step right over such settings...

> Speaking for myself, an opt-in dialog would make me feel better about opting in - I would view it as "acting in good faith" (if I am given a choice, I would more likely trust that tracking data is not abused).

That of course is true, maybe you want to start a markdown page on the documentation for QOwnNotes of what is tracked. You would only basically only need to search for `sendVisitIfEnabled` and `sendEventIfEnabled`. The information is anonymized by Matomo and removed after a few month...

> I also agree that right now most users don't care, but they should, and privacy is a growing concern even for non-technical users. I think in the long term people will begin to value control and safe/conservative defaults as a fundamental indicator of software quality (one that I'm already willing to pay for).

Yeah, wouldn't it be great if more people would think so... Currently I can't even finance server rent with the occasional donation. :grin: 

But still, everyone is free to turn metrics off and hardly anyone would bother to turn it on, because most users don't care about the software they use, they just want to use it (and that's also ok).

**Comment by pbek** [comment]
I will close this until there is more information.
