### ISSUE TITLE
Suggestion: backlinks

### ISSUE THREAD

**Issue by visika** [pbek/QOwnNotes#1717]
Many note-takers are enjoying the backlinks feature as seen in [Roam](https://roamresearch.com/).

It could be useful (maybe in the form of a script) to implement that here too.

**Comment by pbek** [comment]
Can you please describe what the "backlinks feature" does and how it should look like in Markdown?

**Comment by visika** [comment]
Sure. Backlinks keeps track of the places where the current note has been mentioned.
A backlinks panel would list all the notes in which there is a link pointing to the current note.
This is useful to discover connections between topics, ideas, people that we didn't purposely make.

I suppose the process of creating a link would not differ from what currently is in Markdown.
The work should be done from a scraper that looks through the notes in search of links.

Similar implementations may be found in [org-roam](https://github.com/jethrokuan/org-roam/), [Obsidian](https://obsidian.md/) (not open source).

**Comment by pbek** [comment]
Thank you for your suggestion.
Such a thing could be placed into the navigation panel.
Of course creating a directory of backlinks would be a bit resource hungry and would need to be done completely every time the note folder is reloaded and partly when a note is stored.

**Comment by Gregory-K** [comment]
"Corresponding note references" (naming stolen from Drupal, https://www.drupal.org/project/cnr) is a nice feature, though, I think it needs a database in order work fast enough to be useful.

Can we use the `notes.sqlite` for something like that and refresh it on "start" or manually?

**Comment by pbek** [comment]
> Can we use the notes.sqlite for something like that and refresh it on "start" or manually?

That would be a lot of work and even take more cpu time to sync that every time the note folder is reloaded.

**Comment by Gregory-K** [comment]
suggested steps  
- feature enabled and placed into a panel
- create references (links to other notes)
- press a button to create corresponding references or check an option to do it only on program start

OK, it will not be fully dynamic and "live" but it will fill certain needs.  
Now, about the database use or not, of course, you know what is best.  

thought:  
... create a specific header or footer block (inside the note) where note references will be updated  
_I know that this is imposing a certain note template/structure, but it will also work with plain text/md editors/readers_

**Comment by Waqar144** [comment]
It would be better if its not 'auto refreshed' at all, just once on startup.

**Comment by pbek** [comment]
My first attempt...

- There now is a **backlink widget** in the navigation panel to show notes that link
  to the current note (for [#1717](https://github.com/pbek/QOwnNotes/issues/1717))
  - You can click on the note to open it
  - You can search through the note names of the backlinks

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by visika** [comment]
That's fantastic to hear. I tried that and it works very nicely!

**Comment by pbek** [comment]
This is what happened in the last release:

## 24.9.1
- The **backlink widget** in the navigation panel now also shows the links in the notes
  to the current note (for [#1717](https://github.com/pbek/QOwnNotes/issues/1717))
  - By clicking on them, you can open the note and search for the link

**Comment by pbek** [comment]
> That's fantastic to hear. I tried that and it works very nicely!

Thank you for testing!

**Comment by pbek** [comment]
@visika, can you please help me? In what way does your mind need to work to really make use out of backlinks? 😊 I look at them and think "nice, but what do I need to know that for" 😆. Anyway, I'll add more features to the widget today...

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by dohliam** [comment]
@pbek Thanks for implementing this, great to see this feature being added as a default. Right now it does not seem to be working with double-bracketed relative links (as in the backlinks script for QOwnNotes). Just wondering what kind of links does the widget expect -- for example, absolute links with full filepaths in Markdown or wiki-style format?

* Example of wiki-style link syntax: `[[local note]]` or `[[local note|Link text]]` (both link to a note called `local-note.md` on disk)
* Example of Markdown-style link syntax:
  * Absolute path: `[Link text](/home/username/notes/subfolder/local-note.md)`
  * Relative link: `[Link text](local-note.md)`
  * Relative link with assumed file extension: `[Link text](local-note)`

(It would be fantastic if the default link style could be configurable in settings.)

**Comment by pbek** [comment]
No, supported is only what's supported by QOwnNotes itself, see:

https://github.com/pbek/QOwnNotes/blob/024b1983dc3cf011d01caae8283bc4054c26a00d/src/entities/note.cpp#L3174-L3228

Dealing with that regular expressions code is a little bit too complex for settings.

**Comment by dohliam** [comment]
Thanks. I did a few tests and couldn't get links to notes in other subfolders to work even with full paths. I see that there is code already for handling relative paths though, so not sure if there is a different way to link them that I haven't tried.

Here are the results of some tests with the latest version of the widget:

* Page in current folder with filename + extension: `[Link text](filename.md)` (works)
* Page in current folder with filename and no extension: `[Link text](filename)` (doesn't work)
* Link to note in different subfolder with relative path: `[Link text](../foldername/filename.md)` (doesn't work)
* Link to note in different subfolder with absolute path and home tilde: `[Link text](~/notes/foldername/filename.md)` (doesn't work)
* Link to note in different subfolder with full absolute path: `[Link text](/home/username/notes/foldername/filename.md)` (doesn't work)
* Link to note in different subfolder with full absolute path: `[Link text](/home/username/notes/foldername/filename.md)` (doesn't work)

**Comment by dohliam** [comment]
> @visika, can you please help me? In what way does your mind need to work to really make use out of backlinks? 😊 I look at them and think "nice, but what do I need to know that for" 😆. Anyway, I'll add more features to the widget today...

I make heavy use of backlinks (using the [backlinks script](https://github.com/qownnotes/scripts/tree/master/backlinks)) and find it extremely useful to be able to see at a glance the connections between one note and others in a knowledge base. In general, the more links you have and the more closely interlinked they are, the more useful backlinks become.

This is tied to the concept of bidirectional linking, which the Logseq docs talk about [here](https://docs.logseq.com/#/page/why%20linking%20matters).

However, I think it's important to understand that links to "notes" (i.e., local links) are fundamentally different from links to "websites" (i.e., external links), and most programs that have bidirectional linking / backlinks support treat them differently as well. For example, Logseq, Roam, and Obsidian all use the _de facto_ standard "wiki-links" format (e.g., `[[link name]]`) for local links and the standard Markdown link format for external links.

One of the reasons for this is that, as mentioned above, for backlinks to be useful, notes have to already be heavily interlinked. And for that to be practical, linking within note text has to be effortless. This is different from adding a link to an external site, where you are likely copy-pasting text from a web browser rather than typing out the full URL by hand.

For local linking, in most cases, you should be able to just surround parts of the note text in double brackets and get a working link, with no need to spend any further time thinking about the file structure, filename, or file extension of the note you are linking to. For that reason it is helpful if the link is case-insensitive and disregards spaces (or replaces them with hyphens etc). This is currently already possible to do in QOwnNotes using the [wiki-links script](https://github.com/qownnotes/scripts/tree/master/wiki-links), which was originally developed due to frustration with trying to link local notes using regular Markdown syntax.

Here is an example of some locally-linked note text:

```
This is some note text in a typical note. From here it may be 
useful to link [[another note]], or even a [[list of related 
concepts]]. For more information you might want to look at 
[[this note]], or [[that note]], or the [[other note]] which
go into more detail. Linking to a [[name/note in a different 
directory]] can be cumbersome using external link syntax.
```

Here is the same note but using Markdown-style links for the local note files:

```
This is some note text in a typical note. From here it may be 
useful to link [another note](another-note.md), or even a [list 
of related concepts](list-of-related-concepts.md). For more 
information you might want to look at [this note](this-note.md), 
or [that note](that-note.md), or the [other note](other-note.md) 
which go into more detail. Linking to a [note in a different 
directory](/home/username/notes/name/note-in-a-different-directory.md) 
can be cumbersome using external link syntax.
```

As you can see, the wiki-links style of linking (for local notes) is somewhat easier to read and significantly easier to write without breaking one's train of thought. This leads to heavily-interlinked notes, which in turn make backlinks useful.

It would be great if the current backlinks widget could make the backlinks script unnecessary, but that might need to wait until QOwnNotes has built-in support for wiki-style links.

**Comment by pbek** [comment]
Thank you for the testing!

>     * Page in current folder with filename and no extension: `[Link text](filename)` (doesn't work)

But QOwnNotes never supported such a style anyway, did it?

> 
>     * Link to note in different subfolder with relative path: `[Link text](../foldername/filename.md)` (doesn't work)

I hoped I had those covered, need to look how hard those links are to support.

> 
>     * Link to note in different subfolder with absolute path and home tilde: `[Link text](~/notes/foldername/filename.md)` (doesn't work)

I can't remember supporting a shell `~`, also bad for portability.

> 
>     * Link to note in different subfolder with full absolute path: `[Link text](/home/username/notes/foldername/filename.md)` (doesn't work)

Bad for portability.

> 
>     * Link to note in different subfolder with full absolute path: `[Link text](/home/username/notes/foldername/filename.md)` (doesn't work)

Also bad for portability.

**Comment by pbek** [comment]
Ah, I already forgot the backlink script. 😊

The problem main problem with alternative link styles (as much comfortable those would be to later detect the difference to other links) is (beside portability to other Markdown renderer) that it's not supported by md4c for HTML conversion. And thus there is no code block detection and will cause issues all the time. ☹️

We already do some link replacements in QOwnNotes and there are open GitHub issues because of that. 😬

I myself just use the "Insert note link" dialog to link to other notes.

**Comment by pbek** [comment]
Btw. you forgot the old legacy `note://` note links, those should also work. 😉

**Comment by dohliam** [comment]
Thanks -- I had never heard of the `note://` protocol for links before. I tried it and it worked in QOwnNotes (i.e., successfully linked to another note), so clicking on the resulting link opens the corresponding note, but there is no baclink displayed in the widget back to the original page. Same with `<>` links.

The mention of portability got me thinking that perhaps what I had missed was the `file://` protocol for local links, but although these also work to _open_ notes, they don't seem to show up in the backlinks widget either. I'll update my comment above with these.

For the record, what is currently considered to be the most portable way of handling local links in QOwnNotes? It would be good to document this as there are clearly a lot of different possibilities out there! :sweat_smile:

**Comment by pbek** [comment]
I can see `<...>` and `note://`.

![image](https://github.com/user-attachments/assets/a341d47d-a6b2-422e-afd6-af81cba47f5a)

**Comment by pbek** [comment]
> For the record, what is currently considered to be the most portable way of handling local links in QOwnNotes? 

The links generated by the note link dialog. Also, links to headings can be generated that way.

**Comment by pbek** [comment]
> * Link to note in different subfolder with relative path: `[Link text](../foldername/filename.md)` (doesn't work)

They seem to work if `/` is escaped as `%2F` (as they are created by the note link dialog) 🤔

**Comment by pbek** [comment]
I hope this will not break stuff... 😅

## 24.9.3
- In the **backlink widget** and the automatic link transformation, when notes are
  renamed, now relative links with `/` and urlencoded `/` (as `%2F`) are both supported
  (for [#1717](https://github.com/pbek/QOwnNotes/issues/1717))
  - The note link dialog will now not urlencode `/` anymore

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
I already found an issue where duplicate backlinks are tracked and shown, need to rethink that part.

**Comment by pbek** [comment]
## 24.9.4
- An issue with the **backlink widget** showing duplicate items panel was fixed
  (for [#1717](https://github.com/pbek/QOwnNotes/issues/1717))

There now is a new release, could you please test it and report if it works for you?
