### ISSUE TITLE
[Windows] Click systray icon doesn't activate QOwnNotes window

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#176]
When I click system tray icon, QOwnNotes window will just show/hide its main window.
It doesn't change priority of window.
So, if I activate an another application window after hide QOwnNotes window, QOwnNotes window will be restored under that application window when I click system tray icon.
I must click on taskbar icon to activate QOwnNotes window.
It is better to restore QOwnNotes window at the top of windows when I click system tray icon, isn't it ?

An another problem is the case of minimized window.

1. Enable Show in system tray option.
1. Minimized QOwnNotes window to hide QOwnNotes window.
1. Click system tray icon.
1. Click system tray icon to show QOwnNotes window.

In this case, QOwnNotes window is still minimized and hidden.
It is better to restore from minimized when I click system tray icon, isn't it ?

**Comment by pbek** [comment]
thank you for reporting, I will take a look at it

**Comment by pbek** [comment]
for 16.05.18...

- in the tray icon there now is a new context menu entry for opening QOwnNotes
  (for [Issue #176](https://github.com/pbek/QOwnNotes/issues/176))
- left clicking on the tray icon now doesn't show or hide the app under OS X 
  because this will also also trigger the context menu
- opening QOwnNotes with the tray icon or the context menu entry will also 
  un-minimize the window and bring it to the front
  (for [Issue #176](https://github.com/pbek/QOwnNotes/issues/176))

**Comment by pbek** [comment]
Can you please test if it works for you and report back?
