### ISSUE TITLE
Does QOwnNotes support math formulae

### ISSUE THREAD

**Issue by sonulohani** [pbek/QOwnNotes#1784]
This is not an issue but rather query on does this software renders math formulae.

**Comment by pbek** [comment]
Basically it's still like in #593.
But there are scripts like `Latex Math` in the script repository. And you could write your own renderer for the preview.

**Comment by pbek** [comment]
https://github.com/qownnotes/scripts/tree/master/latex-math

**Comment by Vectornaut** [comment]
> Basically it's still like in #593. But there are scripts like `Latex Math` in the script repository. And you could write your own renderer for the preview.

Could you provide some pointers on how the folks who want math support would integrate our own renderer into QOwnNotes? Would we write a plugin, or change the internals of the `HtmlPreviewWidget` class? Could it be as simple as basing HtmlPreviewWidget on [`QWebEngineView`](https://doc.qt.io/qt-6/qwebengineview.html) instead of `QLiteHtmlWidget`, as discussed in [this StackOverflow answer](https://stackoverflow.com/a/56761107)?

The inability of QOwnNotes to render LaTeX directly (rather than rendering it externally and importing it as images, like all the solutions I've seen so far) is a big enough pain for me that I would seriously consider implementing it myself at some point. Maybe @Aganel, @r00tr4v3n, @lindXdeep, @sonulohani, @Siedlerchr, and @Netsaver feel the same way?

**Comment by pbek** [comment]
You can do everything with https://www.qownnotes.org/scripting/hooks.html#notetomarkdownhtmlhook in a script. You can embed HTML (or an image in HTML) that way.

Did you look at https://github.com/qownnotes/scripts/blob/master/latex-math/latex-math.qml? It uses for example an external tool.

E.g. https://github.com/qownnotes/scripts/tree/master/markdown-it uses a JS library to generate the HTML.

**Comment by pbek** [comment]
Or are we talking about a C++ implementation?

**Comment by Vectornaut** [comment]
> You can embed HTML [...] that way.

I just learned that [KaTeX](https://katex.org/) can render LaTeX directly to HTML, so maybe the HTML injection is the way to go! When I have time, maybe I'll try to modify `latex-math.qml` by replacing the

 - *call external executable* → *return image tag*

pipeline with a

 - *call KaTeX* → *return output HTML*

pipeline.

> Or are we talking about a C++ implementation?

That might be feasible, if you're interested in it. There's a C++ library, [*latexpp*](https://github.com/goldsborough/latexpp), that renders LaTeX to HTML by running KaTeX in the [V8](https://github.com/v8/v8) JavaScript engine.

**Comment by pbek** [comment]
I don't think I want to bloat the app with a V8 JS engine and make it build in dozens of build systems. 😆 

So a script solution would be best.
