### ISSUE TITLE
Utilize subfolders for navigation

### ISSUE THREAD

**Issue by prat0088** [pbek/QOwnNotes#183]
I rely heavily on subfolders for organization.  It would be nice to to be able to filter my notes list down by the subfolders somehow.

By the way, QOwnNotes is *the* I've been searching for that I didn't believe would exist.  Markdown with syntax highlighting.  Search. TOC.  Search.  Windows.  Hooray.

**Comment by pbek** [comment]
Thank you for your kind words. Yes, it didn't exist, that was the reason I started to create it. :smile_cat: 

>  It would be nice to to be able to filter my notes list down by the subfolders somehow.

Could you please describe what you mean.
Note that you can already turn on a folder selector in the settings and there also is tagging.

**Comment by prat0088** [comment]
> Note that you can already turn on a folder selector in the settings and there also is tagging.

I use plain text editors on mobile so I can't tag there.  I also prefer to use subfolders for organization because more applications can navigate subfolders than read an .sqlite database of tags.  

I do see a list of folders in a drop-down list, but only the top level folder.  If I add folder "Notes" to QOwnNotes, "Notes" will display in the dropdown but none of its subfolders.

**Comment by pbek** [comment]
And now you don't want to add each folder individually, but to be able to view all sub-folders in a tree?
Hm, that would add a lot of new complexity to QOwnNotes...

**Comment by LightTemplar** [comment]
I would like to use such a functionality too. 
I have a "Projects" Folder, where all projects have own subfolders with predefined structure, and I would very like to store also related Notes there. If the QOwnNotes would search all text and .md files through all subfolders - it would be great!
May be later also with a searching ability by the name of an owning folder...

**Comment by pbek** [comment]
Note tree: I don't know yet if this will ever happen, since it adds a ton of complexity and side effects.

**Comment by LightTemplar** [comment]
I understand.But I also understand, the more people will need it, the more chance you will find a way to implement it ;)
Thanks for your work, the App Heartbeats from my installation will beat definitive more offen =)

**Comment by pbek** [comment]
:smile_cat:

**Comment by pbek** [comment]
I started to work on that issue in a branch <https://github.com/pbek/QOwnNotes/tree/feature/note-tree>. A lot of works and troubles to solve awaits there..

**Comment by Maboroshy** [comment]
Is the "media don't follow note" issue I've posted in the scope for this branch?
I ask because I'm close to finishing first part of my "back-end" shell script mainly focused on inbox. After some polish I plan to release it. Next to inbox I was going to work on links part: conversion, linked files handling and so on. 
Will note trees be just an interface change or there are going to be some changes in "media" handling?

**Comment by pbek** [comment]
media issue: Can you please ask about that in the issue you mean?

A lot of changes has to be made to make that note tree work... I guess the media folder will stay in the note folder and not in the sub folders, but I'm not sure yet....

**Comment by Maboroshy** [comment]
[This one](https://github.com/pbek/QOwnNotes/issues/204)
Having "media" stored in "root" note folder will solve the issue above. It was one of the "modes" I've planned. But I've had current folders as sub-folders from your model because the app currently is only about folders.

The other was having a "media" directory for each individual note. I currently have that with web pages turned to notes as most browsers are making "web page_files" dirs when they save web pages. 

Another big thing is expanding from "media" to generally "attachments" - any file types linked in/to note.

**Comment by pbek** [comment]
You have many plans...
QOwnNotes already support relative links to other files...

**Comment by Maboroshy** [comment]
It does. But as far as I know it doesn't do the "copy to media and link to it" trick for them. 

One of "modes" for file links can be using reference linking instead of in-text. That way all "attachments" can be listed in one place.

You know that I can go on and on. :-)

**Comment by pbek** [comment]
I'm not always sure what you are talking about, but please don't let us discuss those ideas in this issue, @Maboroshy. ;)

**Comment by pbek** [comment]
@prat0088 and @LightTemplar, I now released a pre-alpha of the **note sub-folder tree integration** in version 16.06.14.

- first pre-alpha release of the **note sub-folder tree integration**
	- per default notes will be shown as a list in a new note tree widget
	- all functionality of the old note list was integrated into the new note 
	  tree and should work as it used to
	- for each configured note folder you can now check a checkbox 
	  `Show subfolders in note list` to show the subfolders of the note folder
	- if the checkbox is checked notes of a note folder and the subfolders are 
	  shown as tree instead of a list
	- editing notes in subfolders should already work in most cases, but you 
	  cannot create new notes in subfolders yet
	- a lot more work has to be done to be able to use tags, media files, 
	  note versioning and trash, moving notes in subfolders, updating the 
	  position of edited notes in the tree and so on

Could you please test it and tell me what you think?

**Comment by pbek** [comment]
@Maboroshy, of course you are also welcome to test the new release!

**Comment by Maboroshy** [comment]
I've typed quite a lot text about ergonomics, optimal number of items, my views on using file system for all kinds of things. But I've deleted all that to type just the summary stuff.

You have a good tag panel - use it for the subfolders too! Cut it in half subfolder tree on top, tag tree on bottom, note list on the right. Most of the popular note apps do like this, it's familiar and well tested solution.

I thinks users rarely need to see the content of two folders, we mostly search for something specific. With tag panel I: 
click tag
click note
click another tag
click note and so on. 
Need to use the tree and scroll a lot - I should reorganize my tags. 

I have about 4-5 times less tags than notes, so when I've tried new tree interface it was like: 
open folder
click note
cli... hell my folder is under all those notes, should I scroll down or should I close current folder?
ok I'm scrolling, open folder, damn my note is somewhere below, need to scroll some more
I've found it! Click note.
now there was some folder in the middle, need to scroll up to search for it. I have about 3 screens of stuff to scroll and search here
ok I've closed all the folders... what was I've been searching for?

And there can be nested subfolders... 

I'm sorry if my thoughts above are somehow harsh. I just want your app to be the best. 

I'll try to post some more specific UI tests later. I've started them but that thoughts above overwhelmed me.

**Comment by pbek** [comment]
Having the sub folders in a different tree widget sounds like a good idea, too bad I had to re-implement the note list before you had it. :)

**Comment by Maboroshy** [comment]
Anyway that's going to be big step forward for the app. Especially for me because I like using file system based hacks. Which folders it doesn't show in current version? Only hidden and "media"?

**Comment by pbek** [comment]
only `.`, `..` and `media` are ignored

**Comment by LightTemplar** [comment]
@pbek, I agree with @Maboroshy about splitting folders tree and Notes. It will be also easier to create a Note under needed Folder. A selected Folder with Tag can serve as AND condition for filter Notes. 
There are also some use cases for showing notes not only direct under selected folder,but also under all nested folder. But this won't be liked by all. May be a switch on the upper panel ?

**Comment by Maboroshy** [comment]
"AND" can be good idea if it is correctly displayed by UI. Something like this:
Select folder. All tags absent from the folder are greyed out, number of notes for present tags count only notes in this folder. 

That way new user will understand that tag space is the same for whole "root" folder. It would also will be useful if drag'n'drop tagging will ever be implemented in the future.
Would also be good to have an option to hide greyed out tags for advanced users who have lot of tags and use folders to kind of sort them.

Also +1 for option about recursive note list. I wrote the same thought about tags earlier. But I have all that switches on the left panel.  :sunglasses:

**Comment by pbek** [comment]
We'll see, too bad I have to throw away two thirds of what I did this week...

**Comment by pbek** [comment]
To be sure we are talking about the same thing... This is how it should look like, right?

![screenshot_20160702_122040](https://cloud.githubusercontent.com/assets/1798101/16539843/8155ddd8-404f-11e6-80e1-f7c328d9b652.png)

**Comment by Maboroshy** [comment]
Folder tree should go to the top. It's there in most note apps which use folders/tags scheme. Root folder drop-down selector should logically go above folder tree.

The folder tree should be just like the tag one - no notes shown and a counter.

**Comment by Maboroshy** [comment]
It would be great if user can move the split line of this new navigation pane, like the one between note list and note header structure.

**Comment by pbek** [comment]
> Folder tree should go to the top. 
makes sense

> Root folder drop-down selector should logically go above folder tree.
I will have to see how to do that since either tags and sub folders are optional...

**Comment by LightTemplar** [comment]
> I will have to see how to do that since either tags and sub folders are optional...
If Folder tree goes up, then I think, it will be ok to have the Root Selector always on top of the first column, regardless of whether it will be Folder Tree, Tags, or Notes. Since the first column depends of settings of the Root Folder. 
And, since list of tags is different for each Root Folder, and could be also empty, may be let the presence of Tags be settable via Root Folder settings, as the presence of Folder Tree? Just a suggestion.

**Comment by pbek** [comment]
tags are currently stored only in the note folder, not in each note sub folder

**Comment by pbek** [comment]
I created a new release 16.07.0 to play with:

- there now is a new experimental **note sub folder tree** instead of the 
  folders and notes in the same note tree
   - notes are filtered by note sub folder when clicked on a note sub folder
   - searching for note sub folders is not implemented yet

**Comment by LightTemplar** [comment]
No no! I didn't mean to store tags in each subfolder!
I meant to store a setting for each Root Folder, whether it has tags, or not.

**Comment by pbek** [comment]
so still different tags for different note sub folders? or just one set of tags for all sub folders (including the root folder)

**Comment by LightTemplar** [comment]
I am for one set of tags for the whole root folder and its subfolders.

**Comment by Maboroshy** [comment]
I'm on phone, so I'll be less chatty that usual.

Personally I think that after you implement subfolders for the most users it is the root selector which will become optional. It will become more like an "account" selector and mostly be used when you have one folder syncing and one doesn't.

There should be one set of tags, tag db and media dir per root, so you can easily move notes between subfolders without them losing tags and linked media.

Tags in UI however can be filtered or greyed out.

**Comment by Maboroshy** [comment]
I think that moving tags between db's may complicate the things up.

**Comment by pbek** [comment]
from the v16.07.1 release:
- added more features to the **note sub folder tree**
    - there are now tooltips and a note count for note sub folder tree items
    - new notes are now created in the correct note sub folder
    - the current note sub folder will now be stored for each note folder, so
      that it gets remembered when note folders are switched
    - you can now search for note sub folders in the note sub folder line edit

**Comment by Maboroshy** [comment]
I've tested the new version. It's absolutely there in terms of conception. But as with any alpha some peaces are out of place. Here's what I've found on the first run:

1) Folder tree have the limit of the number of shown characters after which it goes "...". On my system it's about 10 for first level, 5 for second level, 3 for third. So starting from second level it looks bad.
 
Since the length of names is fixed, note counter is always at the same place, however note counter of the tag tree moves with tag length. For a neat UI counters should be in a single column.

I guess that widget layout in both occasions is two columns. For folders - first column is fixed, for tags first column is set to fit longest text. On both occasions columns are not linked to pane width.

The solution is making right (counter) column fixed size and stick it to the right border of the pane. Left column should not be fixed and will fit free pane space. Don't know if Qt allows it though. Horizontal scrolling can also be disabled. 

This way the user will imply how much characters he wants to see, and UI will look neat anyway.  In this layout "..." is not needed, it's eating 1-2 characters that could be shown instead of it. Don't know if Qt can do the "fade out" text trick instead of ellipsis. I've found only the hard way [here](http://www.qtcentre.org/threads/64594-fading-effect-when-text-is-too-long) and [here](https://github.com/favoritas37/nokiaDeveloperContentArchive/wiki/Changing-Title-Pane-Text-in-QML-applications) by a quick googling.

2) I guess "Note folder" is a root folder. But it is in line with the first level of sub-folders which is confusing. And the zero root level goes nowhere, to the search icon. I propose putting root folder to the zero level at the top and naming it with the actual folder name like this:  

&#128270; find or cre...
Root folder
&#9507; Sub-folder 1
&#9495; Sub-folder 2

Root folder can have some special icon too, like red folder or something.

Maybe this zero level root folder can be a base for new style root selector. But, since we can't have clickable item which is drop down menu at the same time, it is something to work out.

3) I'll post no more about root folder selector. Oops, already posted. :-)

4) Remember sub-folder works, but opened/closed sub-folders don't get remembered.

5) There are still some tree elements (&#9507;) in the note list, don't remember if they were there before the whole sub-folder thing started. With sub-folder they look confusing.

6) Search works great.

7) When I create a new note, folder tree reloads and forgets open/closed folders and search results. I don't see, why the app needs to reload tree with folders, if the user had done nothing, that may change the folder structure.

**Comment by Maboroshy** [comment]
I've just have had a thought that with the new sub-folder tree QOwnNotes became very close to "the note app of my dreams".

**Comment by pbek** [comment]
thank you for your feedback, @Maboroshy 

1) the QTreeWidget has some problems with auto-resizing, maybe I'll find a woraround
2) I've already tried that and it didn't work, The absolute root is invisible and can't be edited, we would have to sacrifice a whole level just for the root note
4) no they aren't, aren't stored anywhere and I'm not sure if I want to store them. storing the full path of sub folders (that can change from the outside) and trying to find them again was messy enough...
5) that will be removed
7) I hope I find a way around all the inotify messiness...

**Comment by Maboroshy** [comment]
1) It work in Dolphin tree mode that way, maybe there're some clues in its code.
2) Just read it in Qt docs. Sad thing. Maybe it can be worked around by putting root folder in another widget above the tree, the widget that can be used as menu item for root note list but also as a root selector. I should read some more Qt docs to find something useful.
7) As I see it in my pink user world, the folder tree reload is supposed to be triggered by actions that do something with folders within the app. Are you saying that you use inotify to detect such actions? So, as changing content of directory is a directory modification, inotify triggers tree reload?

**Comment by Maboroshy** [comment]
I thought some more and understood the role of inotify in the app that can have files changed externally. I use it the same way in that script of mine. Though not on note files yet.

When I thought about script logic for handling moved notes and their linked files (still not implemented), I was going to use a layer of abstraction between inotify and the link handling function. In brief it's something like this:
1) Scan the file structure and save it to var array;
2) Check inotify changes against array data to detect real file structure change.

Hope this can give you some new ideas to solve the issue.

**Comment by pbek** [comment]
Scanning all files for > 1000 notes can take seconds on a spinning disk... ;)

**Comment by Maboroshy** [comment]
If we're talking about folder tree, than it would a lot lighter, since we scan only for folders.

As for the full scan, it will only take seconds on the app/script start. Also I think that 1000 notes on a spinning disk is a rare case. 

I have an old machine with a spinning disk, and will run some tests if I ever implement such logic.

**Comment by pbek** [comment]
I have about 400 notes in one folder on a iMac with spinning disk and it takes like 8 seconds...
As it is currently implemented all sub folders are loaded into the in-memory note database because reloading a subfolder every time you click on a note subfolder would take too long...

**Comment by Maboroshy** [comment]
So you already have that array as a note db. Can you check inotify events agains it? Or maybe I miss something important.

**Comment by pbek** [comment]
I think that you miss that every note file has to be loaded to see if anything has changed, that takes the bulk of the time.

**Comment by Maboroshy** [comment]
Lets divide two cases:
1) Using additional layer to reduce the number of folder tree reloads;
2) Using additional layer for scanning every note in a folder.

1) In this case file quantity is not the problem. There are no files in the note tree. 

Once the app opens a folder, it has the list of sub-folders and files in db. So when inotify event happens, the app can check it against a db to see, if it's about some sub-folder missing in db. If event is about known sub-folder - there's no need to reload folder tree. If there's some new path unknown to db, db must be reloaded so as folder tree.

Folder scan happens anyway so there's no additional load on disk happening.

2) Scanning every file, as you've tested, it is quite slow on hdd. But there's no need for the app to do it. File list should be enough, isn't it? And, after the list, scan file by file based on inotify events. Isn't it like the app works now?

If some someone really want to scan every note to extend the file structure to the note links structure, this guy is doomed from the very beginning... At least unless he works out some optimizations to divide scanning to slow portions, that won't spin the disk for whole 8 seconds. ;-)

Don't know, maybe I'm all wrong here. I hope it may give you some new ideas.

**Comment by pbek** [comment]
Thank you for your thoughts. But I still have to get the inotify watcher to work in any case...

**Comment by pbek** [comment]
## 16.07.2
- added more features to the **note sub folder tree**
    - the tree decoration was removed in the note list since it should not be
      a tree any more
    - improved the column width setup of the note sub folder tree

**Comment by Maboroshy** [comment]
Tested new version, all good. Looking forward to column width sync for tags and folders though.

Looked for some Qt widgets for item 2 of my propositions. Found no better. 

So I propose moving root selector above folder tree. That way the tree will "grow" out of it like this:

:mag_right: find or creat...
[ **Folder name** ] :arrow_down_small: 
┣ :closed_book: Root
┣ :file_folder: Sub-folder 1
┗ :file_folder: Sub-folder 2

I think that root selector should be optional as it is now. The user would naturally expand his note structure in 3 stages:
1) Single folder without sub-folders, structure pane off. I use the app that way at my job.
2) Single folder with sub-folders, root selector off. That's what I'm going to use on my machine.
3) Several root folders with or without sub-folders.

**Comment by LightTemplar** [comment]
> 4) Remember sub-folder works, but **opened/closed sub-folder state doesn't get remembered.**
I would like to vote extra for this

**Comment by pbek** [comment]
## 16.07.4
- the **expand/collapsed state** in the **note subfolder tree** is now stored 
  and will be restored when the note subfolders are loaded

**Comment by Maboroshy** [comment]
I've just tested new version. Folder tree state save works. Folder tree and tag tree columns were aligned at first and that looked neat. They were fixed width though, so there were only about five letters visible on third folder level. 

I expanded some sub-folder and made some note changes. Tree reload happened and column width was now aligned to longest folder name. Changed folder, came back. Since the app now saves tree state sub-folders were expanded and column width was still fo longest folder name. Collapsed all, out, in. Wight back to default neat look again.

I've tried to rename a note with sub-folders on. Renamed "note" to "note1" - ok, "note1" to "note11" - ok, "note11" to "note" - no action, "note11" to "note111" - ok, "note111" to "note" - no action. 
I opened same folder but with sub-folders off. Renaming worked correctly. 
For some reason first note name is no go for renaming with sub-folders on.

**Comment by pbek** [comment]
Thank you for testing and reporting, I will take a look at that.

**Comment by pbek** [comment]
## 16.07.5
- the columns in the note subfolder tree will now be resized when a folder was 
  expanded or collapsed

**Comment by pbek** [comment]
## 16.07.6
- renaming notes in note subfolders should now work without the "externally 
  removed" error message

**Comment by pbek** [comment]
## 16.07.7
- tried to fix the duplicate file and subfolder listings problem under Windows
  (for [Issue #243](https://github.com/pbek/QOwnNotes/issues/243))
- creating a note in a note sub folder will now not trigger a full rebuild of
  the note index (for [Issue #248](https://github.com/pbek/QOwnNotes/issues/248))
   - on some occasions it only works after a first note was created after 
     QOwnNotes was started
- there now is a context menu in the note subfolder tree where you can
  (for [Issue #246](https://github.com/pbek/QOwnNotes/issues/246))
    - create new notes
    - create new subfolders
    - remove selected subfolders
    - show the subfolder in the file manager

**Comment by pbek** [comment]
## 16.07.8
- you can now also create a note subfolder by typing it into the search field 
  and pressing <kbd>Return</kbd>
- note subfolders deeper than 2nd level can now be used
- note subfolders can now be renamed in the note subfolder tree
- now the root note folder cannot be removed in the note subfolder tree  
- the folders that are about to be delete when removing a note subfolder 
  will now be viewed in the confirmation dialog to make it more clear what 
  will happen

I will now close this issue, please create new feature requests if you are missing something

**Comment by pbek** [comment]
also done in 16.07.8:
- viewing and restoring of note versions from your ownCloud server now works 
  for notes in note subfolders
- viewing trashed notes on your ownCloud server now works in note subfolders,
  as well as restoring them on your server or downloading them directly

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if the new features work for you?

**Comment by msbentley** [comment]
Is the sub-folder/tree feature merged into the main branch yet, or should I check out the above listed branch to play with it? Thanks!

**Comment by pbek** [comment]
@msbentley, it's in `develop` and `master` since July.

**Comment by msbentley** [comment]
Great, thanks - sorry, I completely overlooked the checkbox to enable it!

**Comment by pbek** [comment]
Yes, it's off by default. ;)

**Comment by pbek** [comment]
@msbentley and greetings from Straßgang ;)
