### ISSUE TITLE
Global note search

### ISSUE THREAD

**Issue by prat0088** [pbek/QOwnNotes#186]
An option for global search across folders would be useful to quickly find notes. Basically what exists now, but search all note folders.  It would be faster than using a mouse to select the item in the folder dropdown.

**Comment by pbek** [comment]
Currently all notes of a folder are held in memory to make searching even possible in a sane amount of time without keeping all notes in a database or creating a search index.
Keeping all notes of all folders in memory would increase memory usage dramatically and I don't know if most uses would like to see that... And there are some other reasons why that's not a good idea (for example because of the increased amount of open file handlers to get notification when a file gets modified externally)...

**Comment by DoTheEvo** [comment]
Yeah, this is a serious deal breaker for me :(
I think that one of the core functionality of any note taking application is the ease of finding your notes, while having 100% certainty in the search results.

I personally would gladly pay the RAM price for the full search. How much can text based notes even take...  

I am not sure if this math is sound, but I go to [wikipedia linux article](https://en.wikipedia.org/wiki/Linux), do ctrl+a, save those 11,000+ words to a file, the size of the file is 78.6kB.
So folder with 100 notes the size of wikipedia linux article would take additional 8MB of RAM I assume. I am mighty fine with that.

Though maybe the issue would be slower searching, even if shit is loaded to RAM, load enough of it and it gets slow...  but still might be good idea to have an option to load it all or not.

Hell, I am on ssd, I would even take few seconds waiting for search results of files that are just being opened and were not loaded in to ram, just so that I can get the certainty that my search would work... though of course would prefer faster solutions

I understand the desire to have at its core the simple approach of just having bunch of .md files...  but if its not good enough, fast enough there should be move towards something more

**Comment by pbek** [comment]
@DoTheEvo, RAM is not the issue. Loading time is (e.g. see #291). On a spinning disk this takes a significant amount of time.

But meanwhile there are not just note folders, but also note subfolders. All notes of all note subfolders (of a note folder) are all held in the in-memory database. That would serve your purpose.

**Comment by pbek** [comment]
Not being dependant on QOwnNotes (and thus using simple text files) was one of the main goals of QOwnNotes. Beside that, ownCloud notes also uses them.

**Comment by pbek** [comment]
And of course there are also tags to categorize your notes...

**Comment by DoTheEvo** [comment]
>But meanwhile there are not just note folders, but also note subfolders. All notes of all note subfolders (of a note folder) are all held in the in-memory database. That would serve your purpose.

I dont think I follow. 

All this time I talked about subfolders it seems, which are not searchable when you are in different subfolder
I did not mean to talk about folders, which are I assume for some major switching, between users, or work/home notes, not just for regular notes organization

heres webm of the search that is bothering me, when I am in one subfolder, and I search for a note, i have no idea that some other note can contain those words in some other subfolder unless I go and search them there...

https://i.frogbox.es/h5i

**Comment by pbek** [comment]
Ah, sorry, my misunderstanding. At the time of the initial post there were no note subfolders.

Now I understand what you mean, I fear that's not easily fixable. Most of the note operations are depending on a note subfolder to be selected.

At the moment you could only stop using note subfolder (and also turning them off in the note folder settings) and use tags instead, if that's an option for you.

**Comment by DoTheEvo** [comment]
well, will give tags a try I guess

**Comment by pbek** [comment]
I'm currently running a test-implementation of an "all notes" select-option for note subfolders...

panel: yes, that works with all splitter

**Comment by pbek** [comment]
## 16.08.12
- there now is a new item `All notes` in the note subfolder tree that 
  you can click to search in notes from all subfolders
    - if you create a new note while having that selected the note will 
      be created in the root note folder

@Maboroshy, I guess that could be interesting for you too...

**Comment by pbek** [comment]
@DoTheEvo, there now is a new release, could you please test it and report if the new features work for you?

**Comment by DoTheEvo** [comment]
got it, it works as expected, though only tried for few minutes...
thnx for quick feature implementation

**Comment by pbek** [comment]
if you stumble over any issues, please let me know

**Comment by Maboroshy** [comment]
Works without any issues.

**Comment by pbek** [comment]
Makes me happy, thank you for testing!
