### ISSUE TITLE
Switch name

### ISSUE THREAD

**Issue by Matthias84** [pbek/QOwnNotes#193]
It's pretty confusing, that QOwnNotes is incompatible to the Owncloud ownnotes extension, esp. as it checks dependencies and introduces an parallel API. I would recommend to pick a different name to underline, that the data format is still incompatible?

**Comment by pbek** [comment]
that's why there is: <http://www.qownnotes.org/Knowledge-base/Does-QOwnNotes-support-ownNote>

> checks dependencies

which dependencies are you referring to?

> parallel API

there is no API to file versions and the trash, so I had to write my own, QOwnNotesAPI

> different name to underline

what are you talking of? a different name for QOwnNotes? such a suggestion wouldn't make much sense right now...

**Comment by Matthias84** [comment]
Yes I know switching names of a running project isn't trivial. On the other hand it's bad if both projects share the same name but don't work together. I just read the article to late (which results in frustration if you setup your OC to the requirements).

Yes, dependencies refer to the (cool!) connection checker.

**Comment by pbek** [comment]
> frustration

That is why I tried to make clear which note application QOwnNotes is compatible with in the first sentence on <http://www.qownnotes.org/>

> dependencies

what is it about those "dependencies"?
(you don't need any of them if you don't care about accessing versions or the trash on your ownCloud server)
