### ISSUE TITLE
Public Relations

### ISSUE THREAD

**Issue by Fabijenna** [pbek/QOwnNotes#2034]
#### Expected behaviour

YouTubers check out and post a lot of videos featuring QOwnNotes and giving QON a broader audience / attract new users

#### Actual behavior 
QON is not yet widely known on YT although there is interest; people do not yet talk about QON on YT

I need input about which YouTubers to approach and what I should mention when I ask for a review.

For my own videos I want to make a channel and (after starting) provide weekly content on features or how tos.
If there’s anything that I need or should think about before I build the content pls let me know.

#### Steps to reproduce
Search for „QOwnNotes“ on YouTube 

#### Output from the debug section in the settings dialog
Not applicable 

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

</details>

**Comment by pbek** [comment]
Thank you for your PR efforts! 😁 

The only mentions on YT I'm aware of so far are:

- https://youtu.be/St46dvUruSg?t=3m27s
- https://youtu.be/oSSyLNb8jA8?t=2m19s
- https://youtu.be/U52AQ8I3HHk?t=66
- https://youtu.be/om6iJFnqpI8?t=13m54s

> I need input about which YouTubers to approach and what I should mention when I ask for a review.

The ones with a lot of subscribers? 😆

**Comment by Fabijenna** [comment]
Great, thank you for your input. :-)

**Comment by Fabijenna** [comment]
I emailed a year ago some popular YTers, and now I believe that I‘ll better start with presenting QON‘s strongest features as well as compair QON to other similar apps (can you please mention those note taking apps that you perceive as relevant to compare with?) 

Then might save them time, and make a decision easier.

What should, finally, be the channels name?

TY

**Comment by pbek** [comment]
The USP of QOwnNotes is that it is a native App (not Electron), it is fast, very customizable there is no "vendor lock-in".

> What should, finally, be the channels name?

I don't really follow any reviewers on YT. 😅

**Comment by Fabijenna** [comment]
> I don't really follow any reviewers on YT. 😅

Thank you I did intend to ask what my channel should be named. "QOwnNotes in a nutshell"., maybe?
No worries, bc I already have envisioned a number of YouTubers to contact - that'll be the second step though with my currenct concept. ;-)

**Comment by pbek** [comment]
> What should, finally, be the channels name?

Ah sorry, I thought you were talking about the channel of the other YTers.
"QOwnNotes in a nutshell" sounds nice. 😁

**Comment by Fabijenna** [comment]
Actually I was curious whether you could name some note apps that you’d find relevant to cover, I guess the bigger ones, like Evernote and One Note etc.?

**Comment by pbek** [comment]
People mainly migrate from Evernote and One Note to QON when they don't want to be locked-in into those systems.
QON is more an IDE (Integrated development environment) for note taking, but the output is still markdown files that can be used everywhere. 😁 
People often also come from Joplin...

**Comment by Fabijenna** [comment]
Thanks that matches my ideas,

**Comment by Waqar144** [comment]
Seems like a great initiative +1

**Comment by Waqar144** [comment]
The main things that come to mind,
- We have possibly everything you could ever want I think, too many features, something for everyone
- We are open to improvements and ideas always
- We are totally free in every sense of the word

We don't provide sync, but that's a feature? because setting up your own sync is just very simple nowadays and we don't want users to get locked in, and that locked includes NextCloud/OwnCloud, event though we support them natively.

**Comment by Fabijenna** [comment]
Great, thank you! :-)

**Comment by jg55** [comment]
> Actually I was curious whether you could name some note apps that you’d find relevant to cover as comparisons, I guess the bigger ones, like Evernote and One Note etc.?

Just to chime in here, in my own research, I compared QOwnNotes to the obvious big commercial offerings, but also to Joplin, CherryTree, Zettlr, Boostnote, Zim-Wiki, Standard Notes, TiddlyWiki, Notable, MindForger, RedNotebook, Trilium, VNote, nvALT (which is evolving into nvUltra as I understand it), Obsidian, MyInfo, MyBase, Bear... and even Notion... and the standout features of QOwnNotes IMO (depending on which ones you compare to of course), can be summarized overall as:

- Free, open source, cross-platform
- Open and standard file format with no proprietary databases, no vendor or file lock-in -- universal compatibility
- Lightweight and fast, native compiled code, no heavy dependencies, no electron bloat
- Responsive, active development, good support from developer
- Cloud agnostic, leaves the syncing to a cloud provider of your choice, or roll your own -- use whatever cloud service you prefer, from Dropbox to Nextcloud or ownCloud
- No mobile app, but all standardized files can be edited by many kinds of apps on any platform
- Extensible/scriptable with many examples
- Built-in encryption per note option
- Good, flexible, tabbed MD editor with thoughtful and useful features like simple autocomplete for equations, managing orphaned images and attachments, auto note re-linking to renamed notes, tags, workspaces, optional versioning, todos, etc.

Yes, it's missing some things here and there that other apps have and of course those other apps are also missing things that QOwnNotes offers, but QOwnNotes is very well rounded, covers many scenarios and workflows, and because it is completely open format with a simple file structure, you can use any other tools you want.

I do think people who want a strong mobile experience that has the same features or subset of features of QOwnNotes desktop will likely lean to one of the competitors with strong cloud offerings, but for those who want to work primarily on the desktop in MD (and/or those who are fans of Nextcloud or ownCloud), then QOwnNotes is very hard to beat in general. 

IMO, getting YTers to review QOwnNotes in the context of cross-platform desktop note-taking apps will put QOwnNotes in a very good light if the reviewer can take the time to look at the nuances. The small refinements make a big difference.

Those are my thoughts... and honestly looking for YTers to review it based on their prior reviews of competing apps and in comparison to those apps, could be a good thing as @Fabijenna has mentioned.

**Comment by Fabijenna** [comment]
Thank you for your input, I actually would be ready beginning of April to support you maybe by summarizing your research as the first video on the QOwnNotes channel.

If you like to send me the details of your research, which sounds really amazing, I’d like to read through your work in order to see if I think I can assist

**Comment by jg55** [comment]
Hi @Fabijenna -- great! That's a big contribution you're making to the QOwnNotes community by putting together a YT channel or especially if you develop content for people to help them understand what makes QOwnNotes special.

I'd be very happy to send you my notes -- my "research" (let's use the term very loosely) is spread out in random bits and notes for specific projects of mine after many many hours of testing the various software. I'll try to consolidate them into something intelligible and make them a bit more generic. I'll send you something next week if possible.

**Comment by jg55** [comment]
Quick update -- I just sent you both an email with some notes as promised. Let me know if you didn't get them!

**Comment by Fabijenna** [comment]
I got it, James, and it’s a very interesting list with specific details. I want to present and illustrate this list quite literally and not add much else, and would like to know how to refer to you, as the author of the observations.
What would you like me to tell about you?

**Comment by jg55** [comment]
However you want to use the notes is fine, but I don't need any credit and I do prefer to be just an "anonymous avid note-taker" or just considered part of the "QOwnNotes community" -- I'm a big fan of this software and love the work that the devs have done, and hope that it gets an even bigger audience. It deserves it. 

The notes are obviously filtered through my brain and subjective from my point of view, but as a simple reference data point for what you want to accomplish with your PR to help out QON, use them however you want, but maybe just refer to them to as something like "thoughts collected from the QOwnNotes community of avid note-takers" and then I would suggest to add in your own observations and anyone else's thoughts too. But no credit or referencing me is needed, but I appreciate your thought. And honestly, I think a collective approach to this will point out more nuances that show what is special about QON, those notes are really just a starting point and certainly not comprehensive. Hope that makes sense!

As for the format or style of the first intro on the channel, you seem to have a strong idea of where you want to go with it, I can't speak from the marketing point of view, I'm sure it will be helpful. I know I would have appreciated more things like this when I was searching for (and finally found) QOwnNotes. So I think it's great you're doing this, and the more interesting content, reviews, intros, comparisons, walkthroughs, demos, etc., etc., that are available, that all sounds great IMO.

**Comment by Fabijenna** [comment]
Thank you for your feedback, and your further input!

**Comment by Fabijenna** [comment]
Sorry, this will take a while. If anyone is ready for it, please go ahead. Thx

**Comment by Fabijenna** [comment]
I'm on it, and might present results after 2 or 3 weeks. Thank you for your patience.

**Comment by Fabijenna** [comment]
I'm first making a website, because it might be more comprehensive (also as a process to a video). Would that be added to the documentary, and styled like the documentary? It would make sense imo.

**Comment by Fabijenna** [comment]
[QON-PR-04-21.txt](https://github.com/pbek/QOwnNotes/files/6376929/QON-PR-04-21.txt)

Hi, you might want to use this html page e.g. as a blog entry until I'm still expanding it. Uploaded the text file to convert

**Comment by pbek** [comment]
The "blog posts" in https://www.qownnotes.org/blog/ are markdown files too. There are the files: https://github.com/pbek/QOwnNotes/tree/develop/webpage/src/blog

**Comment by Fabijenna** [comment]
idk nouf about markdown yet but I thought html would be ok. I don't think I can convert it in .md

**Comment by Fabijenna** [comment]
Otherwise I can upload it and you'd link it from blog

**Comment by Fabijenna** [comment]
[Note 2021-04-26T15.15.53.md](https://github.com/pbek/QOwnNotes/files/6377345/Note.2021-04-26T15.15.53.md)

**Comment by pbek** [comment]
The content of MD-PR-QON.md is still html 😅

**Comment by pbek** [comment]
Is there are reason why the article is called `QOwnNotes in a nutshell` when it's primarily about all kinds of other note taking applications?

**Comment by pbek** [comment]
And why should QOwnNotes blog about it (what is the purpose of this blog post)?

**Comment by pbek** [comment]
In my opinion this is something a 3rd party can blog about, because it's the opinion of a 3rd party.

Btw. I rewrote the file in markdown in case anyone needs it: 
[2021-04-26-A-comparison-between-features-of-different-note-taking-apps.md](https://github.com/pbek/QOwnNotes/files/6378609/2021-04-26-A-comparison-between-features-of-different-note-taking-apps.md)

**Comment by Fabijenna** [comment]
My plan was to show QOwnNotes‘ features in an overview and then show each in a video. 
Concerning the time that this needs it’s a huge work, and I’ve decided to postpone my commit

**Comment by pbek** [comment]
As a "3rd party opinion" or "user review" it's great. But I'm not sure how to include such content in the "official blog", that should act as reference and not as space for opinions or speculations, that would only confuse visitors.
But of course it could link to another page, but there already is a page for that: https://www.qownnotes.org/faq/references.html

**Comment by Fabijenna** [comment]
Nice. But then, do you prefer that I only post clear done work, and does the process distract you too much?

Because it was actually not my main intention to get this document in your blog.

It seems that I might confused you.

I will definitely try to communicate my wishes, requests and intentions more clearly.

I let you know.

**Comment by Fabijenna** [comment]
Thank you for your support. 
I have a clearer view now! 👾

**Comment by Fabijenna** [comment]
Sorry, I made a mistake. What a shame. Never mind, please. I get it fixed.

> Seems like a great initiative +1
Thank you very much, I appreciate it.

> The main things that come to mind,
We have possibly everything you could ever want I think, too many features, something for everyone
We are open to improvements and ideas always
We are totally free in every sense of the word
We don't provide sync, but that's a feature? because setting up your own sync is just very simple nowadays and we don't want users to get locked in, and that locked includes NextCloud/OwnCloud, even though we support them natively."

Sounds like these three attributes could need some more elaboration. Are you still with me on this? 
It will be a greenscreen shot with the features in the background, I think 20 minutes would be enough, for a start.

Something else comes to my mind: I read somewhere on a forum that users didn't like the default appearance in QON, could that somehow be helped? E.g. by offering the themes more at reach. Whatever, just a suggestion.

**Comment by jg55** [comment]
Hey guys -- sorry for slow reply, I'm too loaded with client work right now, but I'm silently supporting from afar. I think themes are good BTW.

**Comment by Fabijenna** [comment]
Hi Jason, 
If you can fit it in, I appreciate an input for my vid series. Style, or content, I welcome ideas... Will post here when further.

**Comment by apopticon** [comment]
> * No mobile app, but all standardized files can be edited by many kinds of apps on any platform
There is an app for iOS - https://github.com/phedlund/CloudNotes  also available via app store.
