### ISSUE TITLE
Todo-List Calendar/Tasks Plus app

### ISSUE THREAD

**Issue by diluex** [pbek/QOwnNotes#21]
Not every task ist listed in the todo list windows for me. obviously it isn't a case of tags or other comments. one of two similar tasks is not shown.

**Comment by pbek** [comment]
Hi @diluex, thank you for your report!

How many calendar items (vtodo and vcalendar) do you have in this calendar (todo list) on your ownCloud server? Did you wait long enough so that all items could be loaded from the server?
Tags and kind should not be a problem, they are just attributes in the ics-"file" that comes from the server...

Could I get by any chance access to the calendar so I may take a look at the missing items.
Or could you at least export the todo items that are missing as ics?

**Comment by pbek** [comment]
The new QOwnNotes v0.63 has a lot of performance improvements concerning todo lists, you may want to try it out.

**Comment by diluex** [comment]
sorry, exporting does not work as it is not implemented in the tasks plus app.
only 10/13 tasks are listet. the three have the same deadline (02/29/2016) in common.
does that help? same problem with v. 0.63.
thank you in advance

**Comment by diluex** [comment]
sorry, exporting does not work as it is not implemented in the tasks plus app.
only 10/13 tasks are listet. the three have the same deadline (02/29/2016) in common.
does that help? same problem with v. 0.63.
thank you in advance

**Comment by pbek** [comment]
You can export the calendar as ics in *calendar plus*...

**Comment by pbek** [comment]
I think I found something by myself. Can you please try out version 0.64.
And **Merry Christmas**! :)

**Comment by pbek** [comment]
I'm closing this issue now, please reopen it if you still have troubles.
