### ISSUE TITLE
Trying to make script to export - import whole note to zip

### ISSUE THREAD

**Issue by franciscotudel-overtel** [pbek/QOwnNotes#2102]
Hello I'm trying to make a little script to import export note with images and attachments to zip but don't see a function to iterate on these attached files.

The reason is the need of share notes and import to another instances of the program.

Some similar to:

Export:
Select Destination Folder - Copy note to %temp% - copy attached and media to %temp% - zip files

Import:
Select zip file - Extract to %temp% - Create note - Copy text - Copy media and attached to destination folders.

Thanks!
Program is very nice and powerful! Thanks for your job! :-)

**Comment by pbek** [comment]
It would be a bit tricky to export notes with images and attachments, because they can sit in all kind of places (in your note folder, in some absolute path on your disk, in the web, in Nextcloud Text, ...).

All images and attachments would need to be gathered locally to some place, then the note would need to be modified to mimic those local paths (regardless if where the image was previously).

>  Program is very nice and powerful! Thanks for your job! :-)

Thank you 😉

**Comment by franciscotudel-overtel** [comment]
Oh god! I've no think about all this jejejeje :)
I'll try to iterate the text searching [.....]( - here get the path ... get file ... if i can... rename it... write to new note...and so...
Whe I've something I'll put here.

sorry for my poor english :(

**Comment by pbek** [comment]
The complexity depends on how many use-cases you want to support.
For example when you don't use note sub-folders it's a bit easier because all relative image/attachment links are looking the same.
