### ISSUE TITLE
suggestion - implementing wiki style index allowing the navigation of page via a hierarchy of pages

### ISSUE THREAD

**Issue by wgregori** [pbek/QOwnNotes#211]
Thank you for all your work on QOwnnotes - I've been using a similar note taking software called Zim Notes.  This software allows the user to create a wiki hierarchy of pages.  It's a great organizational tool for larger bodies of information. You can read about it here http://www.zim-wiki.org/ 

The three things that I find indispensable are

1. Page index to the left (allows for the navigation of large body of notes
2. Search box feature
3. The ability to create check lists (using a graphical check box

Thanks for listening :)

Wayne

**Comment by pbek** [comment]
Thank you for your kind words and your suggestions!

> Page index to the left (allows for the navigation of large body of notes

We already have a table of context of all headlines, do you mean something else?

> Search box feature

We can already search through all notes in a folder and in the current note, do you mean something else?

> The ability to create check lists (using a graphical check box

I already thought about that and I'm not sure if that's even possible in our plain text edit field, like Zim (rich text edit) is doing it. Plus I thought it would be great to be notified about tasks outside of QOwnNotes. So I implemented an interface for ownCloud tasks (via CardDAV).

**Comment by pbek** [comment]
I'll close this until there is more information.

**Comment by jcoub** [comment]
Hello,
Writing in this thread instead of opening a new one. I also come from another "personal note" software (Wikidpad), which uses a similar "wiki style index allowing the navigation of page via a hierarchy of pages" as Zim.

I believe this is a very powerful feature for QOwnNote, as it is really helpful to help organise a project/some thoughts.

To me this aspect is two fold:

1. Automate link generation (wiki word / Camel case)
One of the key aspect is the ability to automatically create a link to a "child node" by using CamelCase (or in fact any other form of link), even if the page does not exist yet.
It is currently possible to link to a note with <note://YourNote>, but only an existing one.

2. Having a hierarchical tree of notes in the left pane, allowing to navigate (toggle show/hide of a node) from a "parent node" to a "child node".
See this screenshot found in google image: http://www.medicalnerds.com/wp-content/images/wikidpadss2.jpg (coming from http://www.medicalnerds.com/how-to-make-notes-efficentlywith-wikidpad/)

Would you believe that this approach could be implemented in QOwnNotes? I have not yet tried to configure the folders holding the note, maybe some sort of "folder tree" could be created (by hand) to mimic this approach (although it would lack the "automated" link generation that is so practical).

**Comment by pbek** [comment]
Thank you for your suggestions, @jcoub!

1. Could you please give an example of how that might look like?
2. Hierarchical note folders and notes in one tree were originally implemented and downvoted by to users, so we settled with the current solution... there were users with 1000+ notes in one subfolder, a tree would be a nightmare.

**Comment by jcoub** [comment]
Sorry for the delay in coming back on this issue. In the meanwhile, I've used my Wikidpad wikis on the cloud and the sync is almost good (got some errors though). I'm still pondering whether to move everything out to QOwnNotes + Owncloud, but I'm still using Wikidpad much more (maybe because I'm more used to it?).

The main issue for me is to be able to navigate in a hierarchical tree of notes. For the time, I manage this on QOwnNote by creating my own tree with sub-folders.

However this requires: to create your subfolders, and then create your notes. In Wikidpad, I can create child notes by using CamelCase. Secondly, the notes only appears to the right of the folders (in my configuration). Would there be a way to show them below the folder they belong to?

So to answer your point 1, see http://imgur.com/a/p8528

Regarding your point 2: currently my wikidpad wiki has 640 notes, all stored into the same folder (root). No problem to navigate in app. When editing directly (in folder), it's a bit of a pain and I would actually prefer to have those notes organised according to their hierarchical "place" (i.e. in sub folders).

I hope this makes sense.

**Comment by pbek** [comment]
Thank you for your screenshot. But still there will not be a tree with sub-folders and notes in one tree-widget anywhere in the near future. Too many things would be needed to be rewritten from scratch to make that happen and it wouldn't work together with the current system of viewing notes...
