### ISSUE TITLE
Search text bgcolor on light mode

### ISSUE THREAD

**Issue by piyo-gh** [pbek/QOwnNotes#212]
I'm using in Windows 10.
When I search text with F3 key, editor is active. Background color of searched text is blue.
This is good to see.
But when I search text with search forward button, editor is inactive. Background color of searched text is light gray.
This is hard to recognize.

Maybe this is OS's default color, but it would be nice if it was more clear color.
Is there any chance to be changed this light gray color to different one ?
I tried new darkmode and it is very good for search text bgcolor.
Thank you.

![gif10](https://cloud.githubusercontent.com/assets/18474085/16143281/bde515b6-34a6-11e6-90ce-ce3739f2d541.gif)

![gif20](https://cloud.githubusercontent.com/assets/18474085/16143293/cf263d82-34a6-11e6-9508-13b0f7003f5b.gif)

**Comment by pbek** [comment]
Thank you for reporting, I will take a look at that!

**Comment by pbek** [comment]
Sadly, that's a Windows thing. When searching with `F3` the note text edit has focus and gets the dark background color, when searching with the button the note text edit doesn't have the focus and gets the light background color. I can't give the text edit the focus because that would screw up things and I haven't found a way to change the color...

**Comment by piyo-gh** [comment]
Oh, it is Ok.
Thank you for spending your time. :)
