### ISSUE TITLE
Feature request: Allow unselecting .txt files in the settings-menu

### ISSUE THREAD

**Issue by tragtragtrag** [pbek/QOwnNotes#2236]
#### Expected behaviour

Allow deselecting .txt files as default-files in Qownnotes. I don't need/want .txt files to be shown and scanned (e.g. in the word-search) by Qownnotes.

#### Actual behaviour

.txt and .md files are default-files in Qownnotes. They cannot be deselected in the settings menu (under 'general'), the delete button cannot be pressed for them.

It would be great if you allow to deselect .txt files, this would make it much more easier to handle my work since I have many .txt files in folders and subfolders which I don't want to use. I want Qownnotes to only show the .md files in all these folders/subfolders.

**Comment by pbek** [comment]
That has historical reasons, Nextcloud Notes and QOwnNotes started with txt files, but I guess now I can think about something to make txt (or md) removable without breaking too much.

**Comment by pbek** [comment]
This is much more work than I expected and prone to regressions. 😬

**Comment by pbek** [comment]
## 21.9.9
- the `Note file extensions` section in the *General settings* has now a better
  description and a new `list-remove` icon (for [#2236](https://github.com/pbek/QOwnNotes/issues/2236))
- you are now able to also remove the `md` or `txt` note file extensions in the
  `Note file extensions` section in the *General settings* if you don't want one
  of them to be used to recognize note files in your note folder (for [#2236](https://github.com/pbek/QOwnNotes/issues/2236))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by tragtragtrag** [comment]
Wow, you're handling this really fast!  
I've tested it. With the new version 21.9.9 (Windows) I was able to remove the txt note file extensions in the settings-menu. However, I can still see the txt files in the notes list. Also if I search for a word in all the documents the results from the txt-files are shown as well. I've also tried to restart Qownnotes, there's no change.  Anyway, if this is too much for work you, don't mind, I'll try to solve this issue for myself by replacing these txt-files by another format then.

**Comment by pbek** [comment]
Turns out there were more places where those extensions were hard-coded...

## 21.9.10
- now `md` or `txt` files will not be shown anymore in the note list when they
  were removed from the list in the `Note file extensions` section of the
  *General settings* (for [#2236](https://github.com/pbek/QOwnNotes/issues/2236))
- some tooltips were added to the file extensions and a removal confirmation
  dialog was added to the `Note file extensions` section of the *General settings*
  (for [#2236](https://github.com/pbek/QOwnNotes/issues/2236))

There now is a new release, could you please test it and report if it works for you?

**Comment by tragtragtrag** [comment]
Everything seems to work perfect now!! Thanks a lot, I really appreciate that!

**Comment by pbek** [comment]
Great, thank you for testing!
