### ISSUE TITLE
Feature request : notes drag and drop

### ISSUE THREAD

**Issue by Allistakn** [pbek/QOwnNotes#2240]
First of all, thank you for that amazing software, it really helped me to get out of proprietary solutions. 

Allowing notes to be dragged and dropped from the note list panel to the note subfolders panel  would be a huge upgrade in the workflow. Right now, right click, "move note to", select the right folder, then click again, it's imho a quite convoluted process to sort a lot of notes. Ofc it's possible to do that in the file explorer, but it makes you switch from the sotfware, there is not the display of text, you can't edit on the move and so on.
Is there a specific reason why it's not possible to drag and drop notes ? (Pardon my ignorance, I really do not know if it's huge effort, an impossibility, not a priority etc.)

**Comment by pbek** [comment]
Thank you for your kind words.

Yeah, there are reasons not to do it. One of them is we would lose the ability to easily mark notes with just one mouse button (so that would be a breaking change). Another one is introducing drag and drop would mean a lot of accidently dragged notes with no way to undo the damage (notes may be modified when moved around). (also see #779 or similar)

So I'm still not a big fan of drag and drop, because of the regressions and new issues it will bring... 😬
