### ISSUE TITLE
Search should discard results from encrypted notes

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2254]
#### Expected behaviour

Full text search should not return matches in encrypted notes as they are not relevant. Is there someway for QON to detect which notes are encrypted during the search?

#### Actual behaviour

Full text search resturns matches in encryted notes:

![image](https://user-images.githubusercontent.com/5956570/136695071-8a846f11-9466-409f-b6e3-44dcffad567d.png)

Version: `qownnotes 21.10.2-1`

**Comment by pbek** [comment]
No, there currently isn't a way. To make that possible it would be necessary to parse every note with `Note::hasEncryptedNoteText()` on every note folder reload and every time a note is modified and store that information in the in-memory note database so that methods like `Note::search()` can use that information.

I assume that would make note-folder loading a lot slower.

**Comment by pbek** [comment]
Or maybe just look for `NOTE_TEXT_ENCRYPTION_PRE_STRING` and `NOTE_TEXT_ENCRYPTION_POST_STRING`.

**Comment by pbek** [comment]
But search in encrypted notes would also block finding the headline. 😬

**Comment by sanderboom** [comment]
> But preventing searching in encrypted notes would also block finding the headline of an encrypted note. 😬

That's a no-go... :/

Is encrypted a bool in the sqlite file?
