### ISSUE TITLE
question about the need of qownnotes running on the server

### ISSUE THREAD

**Issue by DoTheEvo** [pbek/QOwnNotes#241]
Not sure if I am getting it right from the description, I had the feeling that I dont really need to run qownnotes on the server to get the basic functionality

>To get more features for your notes with ownCloud, like versioning and trash access, you might also want to install QOwnNotesAPI on your ownCloud server.

But I kinda assumed that it would use basic owncloud api to get the sync working but nothing really happens, just error about not having qownnotes api

![error picture](http://i.imgur.com/5hU5wq4.png)

I love the look and feel and all the options of the qownnotes, but I would like to have them synced on my smartphone. But since I dont run owncloud server and dont really need a payed VPS... I assumed I can just use some of the [owncloud free providers](https://owncloud.org/providers/) to setup basic owncloud and get the notes sync going...  but the qownnotes application wont sync on its own, I have  to run owncloud client application to make the syncing happen.

Also I tried to look around on those free providers options, if I am able to ssh in to the server and add qownnotes, but it seems pretty basic, so I guess theres not that much freedom.

**Comment by pbek** [comment]
Thank you for your praise. Yes, since you can sync with any sync-tool you like you don't need to setup an ownCloud instance in QOwnNotes if you don't have QOwnNotesAPI. But you still can if you want to use the todo lists. QOwnNotesAPI should be available from the Apps section of your ownCloud instance (but it currently has `experimental` status because it isn't approved yet since a small change in the package last week.

Does that answer your question?

**Comment by DoTheEvo** [comment]
Could qownnotes do the sync all by themselves if server-url/username/password are supplied?
Do they do it by themselves if their API is present on the server?

>QOwnNotesAPI should be available from the Apps section of your ownCloud instance

I tried 3 different free providers, they are very limited with their offer and did not find the qownnotes api anywhere. There are more to try...

**Comment by pbek** [comment]
> Could qownnotes do the sync all by themselves if server-url/username/password are supplied in the settings?

No, QOwnNotes is not supposed to do that.

> Do they do it by themselves if their API is present on the server?

Which API?

> I tried 3 different free providers, they are very limited with their offer and did not find the qownnotes api anywhere. There are more to try...

Since then you might also not have the notes app you could ditch ownCloud altogether and sync your notes with for example dropbox...

You could always spin up a [Digital Ocean Droplet](https://www.digitalocean.com/features/one-click-apps/owncloud/?refcode=a46a4d6212ea) two month for free with the 10$ credit from the link...

**Comment by DoTheEvo** [comment]
OK, I got it now, syncinc is expected to be done by another app

>Since then you might also not have the notes app you could ditch ownCloud altogether and sync your notes with for example dropbox...

yeah, for syncining PCs, but for smartphones we only got that myownnotes app which you cant just point to a local directory, you need to poin it to a server. But syncing in it is seamless on the other hand...

thnx for the answers

**Comment by pbek** [comment]
You need to get the ownCloud Notes app working then too for Myownnotes.
