### ISSUE TITLE
Note List Tree Expansion Persistency

### ISSUE THREAD

**Issue by offset-torque** [pbek/QOwnNotes#2520]
Firstly thanks for this gem of application. I have tried many applications like Joplin and Obsidian but always came back to QOwnNotes for its features.

**Context**
I am using `Note List` as `Note Tree`.
I have a modest number of folders containing notes and some of them are always in an expanded state because I continously update notes in that folders.

**Current behaviour**
Whenever I delete a file from a folder or add a file to a folder, `Note Tree` collapses.
I am not sure if this is a bug (probably, because some folders are unaffected) or intended behavior (I hope not) but this should never happen. After adding a note, I have to click around 5-10 folders to expand them again. Then when I add another note, same thing again. Delete a note, more clicks etc.

I don't have a big knowledge base and even now it is tedious to re-expand all folders again and again. With more complex folder structures, this behavior would definitely render the application unusable. Expanding 50-100 folders each time you add/delete a note is very bad user experience and a deal breaker for this type of application.

![qownnotes](https://user-images.githubusercontent.com/84420582/165051447-cea7d56e-58de-4510-8010-9e8992a251f5.png)

**Expected behaviour**
Note tree folders should always keep their collapsed/expanded state whatever happens (for example as in **Obsidian**).

**Alternative solution**
If keeping track of expanded state of folders is **impossible/too much work** then QOwnNotes should at least give the user an option like **`Keep tree notes always expanded`** so all the levels are visible all the time. Although not optimal, this is better than the Sisyphus re-clicking alternative.

**Comment by pbek** [comment]
I guess you are talking about #790, which is still "work in progress" (like the setting in the settings dialog says) 😁 
I guess it's best to deposit your wishes there...

But since there is no persistence of folder information, because all note sub-folders are just folders in the file-system the collapsed-state of the tree items will most likely also never be persisted... 😅 

> Firstly thanks for this gem of application.

Thank you 😉

**Comment by offset-torque** [comment]
I found this exactly same issue in https://github.com/pbek/QOwnNotes/issues/790 as CLOSED:
[Prevent note list panel from collapsing after file name change](https://github.com/pbek/QOwnNotes/issues/2181)

> But since there is no persistence of folder information, because all note sub-folders are just folders in the file-system the collapsed-state of the tree items will most likely also never be persisted...

I understand implementing this is a big effort if there is no persistence structure currently. 

In this case it seems my alternative suggestion is the best workaround: 

> "QOwnNotes should at least give the user an option like **Keep tree notes always expanded** in the **Settings** screen so all the levels are visible all the time."

As I said having at least a fully expanded tree is infinitely better than trying to expand everything again and again. Please give users an option for it. Expanding folders is a job for a computer. Clicking endlessly to reach your notes is a waste of time and an obstacle to note taking workflow.

Now there are at least two issues about this. Considering that **users opening github issues** is a very small percentage of **users experiencing a problem**, I think many people using **Note Tree** option are suffering from this issue silently.

**Comment by offset-torque** [comment]
I don't understand what "depositing there" means. This issue is already mentioned there by you it seems. Is there anything else I should do ?

**Comment by pbek** [comment]
I added the suggestion to the todo list of #790.

**Comment by k3dar** [comment]
Hi,
I vote with all my 20 fingers to "Note List Tree Expansion Persistency"

I hope reaction in #2520 about "most likely never be" is not final :)

There is no persitence of folder information, but i think simple 
function "save current open/close of current folders" be enough,
so if new folder created then ofcourse be closed, 
if current folder be deleted, then not be opened because not exist/show,
but not change actual open/close when creted new folder,
not change when QOwnNotes is exited and reopened...

**Comment by pbek** [comment]
That was fixed a long time ago (possibly by #2928).
