### ISSUE TITLE
MacOSX: Icons too dark in dark mode

### ISSUE THREAD

**Issue by jd666** [pbek/QOwnNotes#259]
When switching on dark mode the Icons are not really lit up and are very difficult to see.
(When running on Linux, I can see the Icons properly lit..)

**Comment by pbek** [comment]
That seems to be a Qt thing under OS X. It works under Linux and Windows. I will see what I can do about that, thank you for reporting.

**Comment by pbek** [comment]
The dark icons are not used at all. It only happens in the release builds made by Travis CI, local release builds work. That's very strange.

**Comment by pbek** [comment]
I finally was able to trace the problem back to `macdeployqt`, which is used in the release process.
Since there is nothing I can do about that I asked on the Qt Forum: [OSX: Wrong theme icons are loaded when app is deployed with macdeployqt](https://forum.qt.io/topic/69572/osx-wrong-theme-icons-are-loaded-when-app-is-deployed-with-macdeployqt)

**Comment by pbek** [comment]
I now filed a bug <https://bugreports.qt.io/browse/QTBUG-54960>.

**Comment by pbek** [comment]
I will close this now since we have to wait for the Qt bug to be fixed, I will update this issue if I know more...

**Comment by pbek** [comment]
I also tried to use some dark icons directly in the project, but `macdeployqt` still removes them...

**Comment by estan** [comment]
It's a shame that there has been no reaction to your bug in Qt (I commented and voted on it just now).

We are running into this problem with macdeployqt in our application as well. In our case it's even worse, because we only ship one icon theme, which means icons go missing.

@pbek: Were you ever able to find a workaround, or do we just have to wait for someone at Qt to get around to it?

**Comment by pbek** [comment]
@estan I'm sorry, I haven't found a workaround yet and the problem still exists in Qt 5.8.0.

**Comment by pbek** [comment]
We even try to use `macdeployqtfix`, but this didn't help neither.
<https://github.com/pbek/QOwnNotes/blob/develop/travis/create-dmg.sh>

**Comment by estan** [comment]
@pbek: I realize now that my problem probably wasn't the one you were having. In my case it was simply that macdeployqt won't deploy the SVG icon engine plugin, despite what the documentation says. That's what made the icons not load for me.

It's been fixed and will be in 5.9.1 (https://codereview.qt-project.org/#/c/195317/).

**Comment by pbek** [comment]
That's an interesting find, I wonder why it works for me... Thank you, @estan

**Comment by jd666** [comment]
@pbek: the dark theme icons are now properly highlighted in the latest version. Has this been built with newer upstream release?

**Comment by pbek** [comment]
That's wonderful, it maybe was fixed with Qt 5.9.1, @jd666. Did it start to work with this release?

**Comment by jd666** [comment]
I think yes. I've been out a few days so I might have missed an intermediate release.
