### ISSUE TITLE
Layout not locked

### ISSUE THREAD

**Issue by GoustiFruit** [pbek/QOwnNotes#2693]
Is there a way to make QOwnNotes remember the way the panels were set the last time?
I set up QOwnNotes with those panels:

| subfolders | notes | editor | preview |

Each panel has its own width. On each restart, their width is messed up.

#### Expected behaviour
I'd like my layout to be restored.

#### Actual behaviour
It is not.

#### Steps to reproduce
Every time I close QOwnNotes and launch it again, the layout is broken.

**Comment by pbek** [comment]
Again, please don't post issues without skipping the parts with settings (and most cases logs) 😅 
The panel configuration is remembered. Unless you switched off the central widget and have maximized your application window (because then the layout manager takes over resizing of the panels to fit your screen).
