### ISSUE TITLE
Unexepected rendering of list items with different indentation setting

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#2744]
![image](https://user-images.githubusercontent.com/5956570/224102315-f625a19f-5374-4c87-a453-7aa2f55e04bd.png)

`qownnotes 23.2.5-1`

For testing:

Note for testing:

```
Note
====

---

1 space:

- test
 - test

---

2 spaces:

- test
  - test

---

3 spaces:

- test
   - test

---

4 spaces:

- test
    - test

---

5 spaces:

- test
     - test

---

6 spaces:

- test
      - test

---

8 spaces:

- test
        - test

```

**Comment by pbek** [comment]
I guess that's the way md4c interprets it.
So a list indent is recognized from 2 to 5 spaces. Seems reasonable to me...
Opinions, @Waqar144?

**Comment by sanderboom** [comment]
> So a list indent is recognized from 2 to 5 spaces. Seems reasonable to me...

If this is the case it would make sense to limit the indent setting to max 5 to prevent unexpected results...

**Comment by pbek** [comment]
Hm, maybe you are right. Hm, what if someone uses more than 5 already... 🤔  Most unlikely I guess...

**Comment by pbek** [comment]
## 23.3.2
- the indent spaces are now limited between 2 and 5 in the settings, because
  that's the range the [md4c](https://github.com/qownnotes/md4c) supports when 
  converting Markdown to HTML (for [#2744](https://github.com/pbek/QOwnNotes/issues/2744))

There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment]
> 

Could be that is what the spec mandates. MD4C follows the spec closely.

**Comment by pbek** [comment]
Could be...
