### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by CitDub** [pbek/QOwnNotes#285]
Hello, I recently have been using your program and I've found it very useful and organized. However, I would like to know if you think you could add some more Markdown Syntax (e,g,. ++Underline++. Superscript: 19^th^, Subscript: H~2~O, ==highlight==, -[] Tasklist,  better table presentation, lists and code, MathJax) perhaps by using the GitHub Flavored Markdown or MultiMarkdown.

Something similar to [remarkable](https://github.com/jamiemcg/remarkable): 
https://jonschlinkert.github.io/remarkable/demo/ 

I found this [concept](https://github.com/knsv/mermaidl) interesting.

I'm really enjoying this program so far, I hope you consider adding some of the above.

![screenshot from 2016-08-11 17-59-46](https://cloud.githubusercontent.com/assets/20964943/17607841/13921ec4-5fee-11e6-8364-3ec15d0042f8.png)

![screenshot from 2016-08-11 18-00-04](https://cloud.githubusercontent.com/assets/20964943/17607843/18ef26d2-5fee-11e6-89cf-0e62a1998513.png)

QOwnNotes:

![screenshot from 2016-08-11 18-02-34](https://cloud.githubusercontent.com/assets/20964943/17607847/22d12394-5fee-11e6-881f-dddc7f194be4.png)

![screenshot from 2016-08-11 18-02-59](https://cloud.githubusercontent.com/assets/20964943/17607852/27918d1a-5fee-11e6-95d0-c23769b71721.png)

**Comment by pbek** [comment]
Thank you for your ideas, but since the markdown highlighting is done by <https://github.com/ali-rantakari/peg-markdown-highlight> and QOwnNotes is no Electron app (aka. browser app, where you could use javascript libraries like remarkable) this all is currently not possible.

By the way... If the 2nd screenshot is from your installation of QOwnNotes, do you have dark mode colors activated on purpose? They only look "good" on dark mode desktop themes. :)

**Comment by CitDub** [comment]
Perhaps in other moment or the other way is possible to add more syntax.
[Remarkable](https://github.com/jamiemcg/remarkable) is  Python.

Thanks,

**Comment by pbek** [comment]
QOwnNotes is C++...
And as long we have no fully fledged browser as preview not much more can be done here either (see #164)...
