### ISSUE TITLE
[F] Support embedded images from nextcloud notes web version

### ISSUE THREAD

**Issue by dh-connect** [pbek/QOwnNotes#2877]
#### Expected behaviour

The nextcloud notes web version stores images in the subfolder .attachments.xxxxxx, qownnotes store images in an image subfolder.
It would be great if qownnotes could display the images created with the web version, currently the qownnotes preview only shows this:

`![History](.attachments.766616/image.png)`

`![Title](.hiddenfolder/image.xxx)`

#### Actual behaviour

no image displayed, only text reference

#### Steps to reproduce

create a note with the web version of notes with an image, and view with qownnotes.

**Comment by pbek** [comment]
Nice, last time I checked images could be just referenced from Nextcloud Files (and I implemented support for that).
I tried uploading an image to a note now and it was placed in the same folder than the note for me:

![image](https://github.com/pbek/QOwnNotes/assets/1798101/6df9f9a3-b52c-4cf0-a6ac-917d4d8821de)

How did you manage to do otherwise?

**Comment by pbek** [comment]
And when I created such a hidden folder myself, it showed fine in the preview too:

![image](https://github.com/pbek/QOwnNotes/assets/1798101/1516e0ab-7c0a-4460-a585-b24e5dfb142f)

**Comment by pbek** [comment]
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.
