### ISSUE TITLE
allow use of templates [enhancement]

### ISSUE THREAD

**Issue by jd666** [pbek/QOwnNotes#296]
A lot of notes are created following a certain repetitive schema and the use of templates would help a lot. (Meeting notes, Daily routines)
Suggested enhancements:
- A specific template folder (configurable?)
- Create note from template by dragging template to note folder
- In Note Editor: jump between special template fields by shortcut (like Alt-Tab)

On Note creation replace template fields with the usual replacements:
- automatic replacement for date/time/timezone (%Y-%m-%d %H:%M:%S %Z)
- automatic replacement for current file name (%s ?)
- automatic replacement for current author (%a ?)

**Comment by pbek** [comment]
Currently you can do a lot of that with a script yourself.
See: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-new-note-headline.qml>
You could for example create a note that starts with `[mn]` (for meeting notes) and decide in the script what text to output.

If you need more information in the `handleNewNoteHeadlineHook()` please let me know.

**Comment by pbek** [comment]
And if you have any questions please let me also know.

**Comment by pbek** [comment]
There will be custom actions in v16.08.16!

**Comment by pbek** [comment]
## 16.08.16
- you are now able to define custom actions that will be shown as menu 
  entry in the scripting menu and optionally in the toolbar as button
    - there is an example for opening the current note with KWrite
      and to create a new note with a custom text at
      [custom-actions.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/custom-actions.qml)
    - there is a small documentation about the function
      `registerCustomAction` and other functions in the
      [scripting documentation](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md#register-a-custom-action)
    - you can also assign shortcuts for your custom actions in the 
      shortcut settings
- added new methods to the scripting engine
    - you can now also get the full file path of the current note
      with `script.currentNote().fullNoteFilePath`
    - you can now register a custom action with `script.registerCustomAction()`
    - you can now create a new note with `script.createNote()`
    - you can now access the clipboard with `script.clipboard()`
    - take a look at the [scripting documentation](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/README.md)
      for more information
- there now is a new example to create a note from a 5pm email with a 
  custom action at
  [note-from-5pm-mail.qml](https://github.com/pbek/QOwnNotes/tree/develop/doc/scripting/note-from-5pm-mail.qml)

@jd666, you should now be able to create note templates that are accessible from a menu and a button toolbar! Could you please be so kind and report your experiences.

**Comment by pbek** [comment]
16.08.16 is now released...

**Comment by muesli** [comment]
I'm really missing this being a standard feature. I must admit I'm not too keen on scripting my notes editor.

**Comment by pbek** [comment]
You would tell a different story if you would know what you are able to do in scripts. :) Static templates are not of much use anyway in QOwnNotes (because by default the headline is the filename of the note)... but you can even create a script to edit static note templates in the the script settings

**Comment by pbek** [comment]
so what feature are you missing exactly @muesli, maybe I can help you

**Comment by FBachofner** [comment]
Hi Patrizio:

I am starting to play with scripting to make notes (new notes) consistent across multiple users/workstations.

A template feature would (presumably) allow for a "template" folder within the QOwnNotes note folder.

Putting *_scripts_* in such a location (which is do-able, since QOwnNotes is agnostic about script location) strikes me as a bad idea, given the potential power of scripts.  [ So now, I would have to sync multiple directories around . . . additional complexity potentially leading to new errors! ]

This alone should probably make the case for a templating feature.

Also, the average user will have nearly zero ability to edit a script, but if they just want to dump some default text into a new note, that would be readily achievable with a simple template . . .

Thanks for for further consideration

**Comment by pbek** [comment]
It *never* is "just text" (starting with the headline). It would lead to a million feature requests that could all be implemented as scripts. I wanted to get around that by implementing the "scripting engine"...

And you are free to place your "template scripts" inside your notes folder anyway.

**Comment by pbek** [comment]
You could even create a script with a lot of text boxes as script settings that could all serve as templates as you described them
.

**Comment by FBachofner** [comment]
I certainly empathize with your concern over "a million feature requests"  !  ;-)

I am intrigued by your comment about creating a "script with a lot of text boxes as script settings."  I wonder if the same could be done with dialog boxes to create a "guided" note taking "app?"

First (separate) hopefully simple script ? coming up in a separate thread . . .

**Comment by cscherrNT** [comment]
The links in this issue don't work anymore, a guide on how to create a template script would be very helpful.

**Comment by pbek** [comment]
You can directly use https://github.com/qownnotes/scripts/blob/master/meeting-note/meeting-note.qml (from the script repository) or use it as "template" for your own script.
