### ISSUE TITLE
Bug? Cannot break line with enter in list

### ISSUE THREAD

**Issue by minthemiddle** [pbek/QOwnNotes#304]
When I have a list and switch to any item in it and try to get a newline pressing `Enter`, it just deletes the `-` at the beginning of the line. If you want to add an entry to the beginning of the list, you have to go in a line before and add it here.

Is this planned or unexpected behaviour?

(`Win 10`, `16.08.18`) 

![enterinlist](https://cloud.githubusercontent.com/assets/1950766/17964419/5f30e808-6ab9-11e6-9f46-21ab6d540606.gif)

**Comment by pbek** [comment]
I will take a look at that, thank you for reporting.

**Comment by pbek** [comment]
This is intended behaviour, because if you are at the end of the line of a list item and press enter a new list item will be created. If you didn't want to create a new list item pressing enter again removes the `- `.
You can always jump to the front of the line to add a new line before the current list item.

**Comment by minthemiddle** [comment]
Ok, fine with me. Could be a topic for the docs.

**Comment by pbek** [comment]
@minthemiddle, you are welcome to create some editor docs on <https://github.com/pbek/QOwnNotes/wiki>
