### ISSUE TITLE
Tags dictate the width of the edit pane

### ISSUE THREAD

**Issue by mlinchitstest** [pbek/QOwnNotes#308]
Currently, the more tags you have the wider the edit pane. This is because tags are forced into one row. 
If you have lots of tags (say more than 10), you can no longer resize the editor pane at all: it takes up much of the real estate.  To see what I am talking about, try adding ten tags to a note and then try to make the editor pane narrower. One way to fix this is to have tags occupy multiple rows when needed or to cut them off with a [...] when there is not enough space.

I know this may not be a common problem—so the issue is not urgent. But might be a good idea to fix for people with smaller screens.

**Comment by pbek** [comment]
Long tag names are already cut off. Maybe I find a solution for your problem.

**Comment by pbek** [comment]
## 16.08.20
- if there are more tags assigned to a note than the width of the edit
  pane allows there now will be used a scrollbar to scroll through the 
  tags, so that the width of the edit pane can still be small

There now is a new release, could you please test it and report if the new features work for you?
