### ISSUE TITLE
[Q] What reason "Find" and "Replace" is not part of "EDIT" menu?

### ISSUE THREAD

**Issue by BsNoSi** [pbek/QOwnNotes#3138]
In almost all Windows programs, Menu Edit contains them (afaik same with Mac). From my point of view, it would increase usability.

**Comment by pbek** [comment]
Because it's a feature of https://github.com/pbek/qmarkdowntextedit/ and not QOwnNotes, and it wouldn't be possible to override the shortcuts if there would be menu entries. 

If people would set another shortcut for e.g. the `Find` action in the main menu, then the original shortcut would still work and that would confuse people. ️🤷🏻

**Comment by pbek** [comment]
I take back everything...

![image](https://github.com/user-attachments/assets/8fba32ac-27d7-4bf1-af07-7cdcb368e131)

So I'm not sure what you were talking about.

**Comment by BsNoSi** [comment]
»This is it« – I was looking for the (typically) simple “Find” and “Replace” entry. To be precise: I was looking for “Search in all notes, regardless which one I am currently in”. Which works fine, I only had to understand that the selected subfolder does not limit the shown notes in the list below.
( I am switching from Joplin, therefore I have a few “How is it done here?” challenges.)

**Comment by pbek** [comment]
You can search for menu actions in the *Help* menu. 😉

**Comment by BsNoSi** [comment]
😱 How cool is that? 👍👍👍👍
