### ISSUE TITLE
Order in which notes are displayed

### ISSUE THREAD

**Issue by lister171254** [pbek/QOwnNotes#32]
I wanted to move my wife's notes from various applications into QOwnNotes. The only way to do this was to export the various files and them create them as plain text QOwnNotes files. 

The notes I created all have the heading and text like
------------
Note 2007-11-01T18.00.01
========================

blahblah
------------

All this works fine, but when the notes are displayed, they are not in the expected order, which is Date/time. So my question is, what is the criteria for sorting the notes in QOwnNotes?

Thanks,

leo

**Comment by pbek** [comment]
Hello Leo,
the default sort order is modification date (last modified file comes first). Optionally you can sort the notes alphabetically (filename).

In my case I just ignored the sort order after I "imported" the notes and when I edited one because it came to the to by itself.

Keep in mind that the filename has to match the first line of the note (plus the `.txt`of the filename at the end). The ownCloud notes app does it this way, so we had to mimic that behaviour.

Does this answer your question.

**Comment by pbek** [comment]
If there would be a note importer in QOwnNotes, what features would you expect / love to see?

**Comment by lister171254** [comment]
Thanks for the quick reply; thought so.
I ended up setting the last access and modified date on the files I created for QOwnNotes to the dates of the original (exported) note. All works fine now and in the right order.

I think a note importer would be an overkill given the various export formats that float around. It only took a day to hack some python code to convert the two different file formats I had into the QOwnNotes format

Thanks

**Comment by pbek** [comment]
Great you solved the problem!
Hehe, I guess not everyone is so adept in coding like you. :wink: 

Yes, for an importer we would need much more user input...

I'll close this issue now (until you have a related question), but feel free to open new issues if you have suggestions or troubles.

Have a great day, Patrizio
