### ISSUE TITLE
Suggestion for enhancement: Write the tags to the fils

### ISSUE THREAD

**Issue by MBuchaus** [pbek/QOwnNotes#338]
Would the Prog be able to write the tags directly to the files (optionally) 
based on the free desktop standard
https://www.freedesktop.org/wiki/CommonExtendedAttributes/
http://log.cedricbonhomme.org/55/65404.html

**Comment by pbek** [comment]
Since that's something that only would work on certain operating systems and filesystems there currently are no plans to do this. It also wouldn't be easy to keep internal tags and tags on files in sync.

But maybe you could use the scripting engine to do this when the notes are written: <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/execute-command-after-note-update.qml>

You may want to ask @Maboroshy, who has experience with extended attributes.

**Comment by Maboroshy** [comment]
I think using xattr can be a bad idea because chances they will be lost during note syncing are high. And syncing back will clear them on source system too.

I'm more about a idea with tags stored in note text with unrenderable markdown code. But it has disadvantages too.

For now I think that portable future-proof notes can use only 3 types of data: file path, file name and plain text. Anything else can be lost on another platform.

**Comment by MBuchaus** [comment]
Your Right I didnt' think of the next/own cloud stripping the tags on sync.  Crap.   there was a problem with that on dropbox and the mac back a year or two ago.  ! crap !

**Comment by pbek** [comment]
## 17.09.6
- added the first alpha version of external note tagging support via the 
  scripting engine (for [Issue #323](https://github.com/pbek/QOwnNotes/issues/323), [Issue #338](https://github.com/pbek/QOwnNotes/issues/338), [Issue #379](https://github.com/pbek/QOwnNotes/issues/379), [Issue #472](https://github.com/pbek/QOwnNotes/issues/472), [Issue #530](https://github.com/pbek/QOwnNotes/issues/530) and [Issue #603](https://github.com/pbek/QOwnNotes/issues/603))
    - as soon as a script is activated that implements the new function
      `noteTaggingHook` note tagging will be handled by that function
    - please install the script [note-tagging.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/note-tagging.qml)
      to test the basic functionality and report in [Issue #530](https://github.com/pbek/QOwnNotes/issues/530).
        - your internal tag database and your notes might get modified 
        - don't use this script on your production note folder, please make a 
          copy of it and test it there!
    - following features should already work via the QOwnNotes user interface
        - initially importing tags like `@tag` from your notes and overwriting
          your current tag assignment
            - you will not loose your tags tree, just the former assignment to notes
            - you can still move tags into other tags
            - if more than one tag has the same name in your tag tree the 
              first hit will be assigned
        - adding a tag to a note will add the tag to the note text        
        - removing a tag from a note will remove the tag from the note text
        - removing of tags in the tag list will remove those tags from your notes
        - renaming of tags in the tag list will rename those tags in your notes
        - bulk tagging of notes in the note list will add those tags to your notes
        - bulk removing of tags from notes in the note list will remove those 
          tags from your notes
    - for more information please take a look at the [scripting documentation](http://docs.qownnotes.org/en/develop/scripting/README.html#noteTaggingHook)

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you with the script [note-tagging.qml](https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/note-tagging.qml)?
