### ISSUE TITLE
Toggling tag / subfolder pane turns off tag visibility in the note

### ISSUE THREAD

**Issue by michael-rowe** [pbek/QOwnNotes#343]
When I turn off the tag / subfolder pane in the Window setting it also turns off the tag visibility in the actual note. Is this by design? I'd like to turn off the tag panel but want to still see the tags in the notes I'm working on. Is this possible?

**Comment by pbek** [comment]
Currently there is no other way to turn off tagging altogether than to turn off the tagging pane for those who doesn't want to use it. Any suggestions?

**Comment by pbek** [comment]
maybe @Maboroshy?

**Comment by Maboroshy** [comment]
I'm started to write some big post about evolution and redefining of the app UI as usual, but there can be short solution...

Merge tag panel with status bar.

Status bar is a huge screen wide panel mostly unused be the app, and as I've understood from the Qt docs any widget can be placed there. There can be the buttons of current tag panel, text form for quick tagging and some extra info on the current note. And it can be toggled on/off by user.

Most other advanced note apps tend having that kind of status bar above note editor though.

**Comment by pbek** [comment]
@Maboroshy, you are the grand master of big posts! :) But not today, so it seems. ;)

Hm, don't you think having tags in the status bar would be very confusing? And I wouldn't be able to create those scrollbars if there are too many tags if they are in the status bar. Beside that what's the point of having it at all then if it can't show status messages any more? :) Maybe we just settle for an other checkbox in the window menu...

**Comment by Maboroshy** [comment]
This week has wear me of a bit.

Your point seems like true. There should be some other solution. 

But there was a rant in my unwritten post that putting yet another toggle for tag panel will break "no pane - no tags" principle of the app UI and will be a beginning of having toggles of every UI element... Which is not bad by itself if that's the direction you want to take.

**Comment by pbek** [comment]
Oh, this week is also for me a very demanding one...

> Which is not bad by itself if that's the direction you want to take.

The "problem" with us humans is, that everyone wants something different...

**Comment by Maboroshy** [comment]
"Be careful what you wish for..."

Personally I'm all for maximum customization. But we have already seen the issues of the users overwhelmed by to many options.

Currently we control UI by panes and by view modes. Pane is the "unit" of UI. Tag panel is linked to this kind of unit. 

Now we make panel a controllable element. It's like you have the list of options like 1, 2, 3, 3.2, 4...
What does 3.2 doing here, it's not in row. Well, it was a special case... But is it really special? If we go to 0.1 level logically next stop is having toggles for tag and sub-folders parts of tag pane, navigation panel, and that's for every view mode.

I'm all for that, because I don't use half of it and will gladly turn it off. But it will take a lot effort to make it look neat without making UI frustratingly complex.

**Comment by pbek** [comment]
Letting the user control everything (the opposite of the Apple way) always adds complexity... So what would be the best course now? :)

**Comment by Maboroshy** [comment]
More user control without complexity? That's hard to get with current UI. Current UI works like more control = more menu items = more complexity. To get beyond that some UI principles need to be changed to be more like "big" apps.

What "big" apps do? They getting their vast tool set from "stacks" for user to place each where and how he sees fit. To go that way the app needs it panes atomized to panels with ability to move each panel and dock it where the user wants. 

And Qt has a platform for that - QDockWidget.

Current view modes will transform to "workspaces" - user-defined sets of panels with adjustable names. 

Window menu will become two short uniformed menus - one with the panel list to toggle each and another to choose, save and delete "workspaces".

This way they will be two real panes left - editor and render.

Of course sane default "workspaces" close to what app has now is must. So that newbie users wouldn't need to change anything. 

If you wanted best course that is the one. :wink:

**Comment by pbek** [comment]
That sounds like a great idea. It leaves me to find out how to use QDockWidgets and if they can be used in the current project without starting from scratch...

But the problem that people will expect to be able to turn on and off elements on the fly with shortcuts still remains...

**Comment by Maboroshy** [comment]
You have already solved that for hiding menu bar.

**Comment by pbek** [comment]
You mean by a lot of checkboxes? :)

**Comment by Maboroshy** [comment]
Maybe I've misunderstood. What did you mean by shortcuts?

**Comment by pbek** [comment]
Keyboard shortcuts. We need menu actions for those (e.g. checkboxes). And so we again have a multitude of menu entries... ;)

**Comment by pbek** [comment]
QDockWidget seems great and no to hard to integrate. But we are pretty restricted where the widgets can be placed: <http://doc.qt.io/qt-5/qdockwidget.html#details>
If we want everything floating there only can be placed in either `Qt::LeftDockWidgetArea` or `Qt::RightDockWidgetArea`. Currently we have up to four columns...

**Comment by Maboroshy** [comment]
[This](https://woboq.com/blog/qdockwidget-changes-in-56.html) article made me think there is some more functionality.
Also why do you exclude bottom and top areas? The good place for the tag panel may be below editor.

**Comment by Maboroshy** [comment]
Maybe there's a need to investigate of render pane can be QDockWidget too instead of being part of central widget, so having vertical editor-render layout would be part of new conception instead of being leftover of the old one. 

But I haven't yet used the Qt app with the moveable widget of this size and don't know how would it work out.

**Comment by pbek** [comment]
Top and bottom are not excluded, but they don't give me an other column. Qt 5.6 features will not let us get around that (beside it has to work down to Qt 5.3).
So far I only know of the QMainWindow that can have QDockWidgets...

**Comment by Maboroshy** [comment]
The video shows that it's possible to but two widgets to the same area as "columns" and this feature is not new. If I've understood correct it was there at least from Qt 4.3.

**Comment by pbek** [comment]
You are right, it really shows two columns. I have to investigate that more!

**Comment by pbek** [comment]
I found workarounds for most of the bugging things. I even found a way to remove the title bar of an dock element to save space (that might be a new checkbox "lock down dock elements").
I'm thinking of introducing dynamic modes where the user can move (or remove) docks as they like and the states of the docks will be stored. Those states can then later be restored for example to turn on and off the preview. The user might define "mode 1" with preview and "mode 2" without preview. There could be shortcuts for those modes... What do you think, @Maboroshy?

**Comment by pbek** [comment]
That would eliminate the need for a lot of checkboxes.

**Comment by pbek** [comment]
@Maboroshy there is a new branch `feature/dockwidgets` in case you want to peek at the progress by building QOwnNotes yourself.
<https://github.com/pbek/QOwnNotes/tree/feature/dockwidgets>

All the panes (even note folders and navigation) are dockable and there is a "lock panels" button to disable the title bars. The placement (even if floating) is already remembered. Of course a lot of work still have to be done, especially integrating with the old behaviors and removing of a lot of old styling and moving around code.

**Comment by Maboroshy** [comment]
> I'm thinking of introducing dynamic modes where the user can move (or remove) docks as they like and the states of the docks will be stored. Those states can then later be restored for example to turn on and off the preview. The user might define "mode 1" with preview and "mode 2" without preview. There could be shortcuts for those modes... What do you think, @Maboroshy?
Sound like the "workspaces" idea I posted. I think there should be some basic management for saving with user-defined name and deleting saved "workspaces"/states. Shortcuts can follow their order like F1 - F10 with an ability to rebind.

Some checkboxes have stay to activate closed panels. But it will be quite short neat list instead of mix of panes and modes like it is now.

So list of panels and list of saved states will cover any combination. And making new features will be adding panels without the need to arrange hard-coded layouts every time.

I'll try building this new branch.

**Comment by Maboroshy** [comment]
I've tried it and it's very cool! Very simple and powerful.

If I understand correctly the layout of this version has no central widget. That creates an empty space between dock areas you have to cover by getting panels together. Without that central widget it also hard to understand where the panels docked, what is the reference point. I do understand that it was made to make editor and render both toggle-able. Maybe you could try putting a version where render and editor are old school panes acting as a central widget. That may be more intuitive.

**Comment by pbek** [comment]
Thank you for your feedback!

That's right, no central widget because that would not have been movable. All dock widgets start in the left area, so the gap is on the right. What reference point do we need in your opinion? Currently preview and editor can be placed vertically and they can even be tab-able. Both wouldn't be able in the same way if one of them or both are a center widget.

**Comment by pbek** [comment]
Later found out that the current "layout" looks hideous in fullscreen / maximized mode. If I can't find a solution to that I really will have to leave the edit (and maybe also the preview) in the content area. Too bad, because I wanted to make the note tag pane also dockable...

**Comment by pbek** [comment]
I finally got around the troubles, the docks are now places where they should and there is no gap at the right any more! Everything (plus the note tags) are still dockable! What do you think, @Maboroshy, my trusted product manager?

**Comment by Maboroshy** [comment]
It works quite good.

Can't check .ui file in designer, for some reason it shows the old layout. You've made the single docking area to work it out, didn't you? That way there's also no way to dock anything screen-wide above or below. But the app currently doesn't have anything suited for that so not a big deal.

For some reason the note editor doesn't show up, but that maybe due to I'm lame at building the app.

Toolbar with panel drop down selector is ugly when vertical, but it's doubled in menu and bindable. 

The lock button could lock the toolbars too. Don't know if it should also lock panel sizes.

I'm not sure that context menu for activating panels is intuitive. It takes little but still some skill to get it with screen full of widgets. Maybe it's worth own place in main menu.

Looks like storing layouts doesn't work yet. Clicking layouts in menu also doesn't affect drop-down selector.

Is menu, status and tool bars are part of saved layout? That way distraction free mode can be just another layout.

Note root selector should be a separate panel instead of embedded into note list.

Sub-folders panel sometimes goes fixed zero size. Need to investigate more what causes it. Maybe that also the building issue of mine.

Preview got some big empty horizontal scroll I don't remember it had.

Overall it's very cool, UI feels like "photoshop" for notes.

**Comment by pbek** [comment]
The ui-file is quite the same (beside removal and addition of some menu entries), the dock handling is done in code. You have to build qownnotes to see what is new.

Everything is encapsulated in dock widgets.

> That way there's also no way to dock anything screen-wide above or below

What do you mean by that? Currently you are able to do everything the layout-checkboxes do and much more.

> For some reason the note editor doesn't show up, but that maybe due to I'm lame at building the app.

Have you turned it on with the proper checkbox? Theses checkboxes will vanish too.

> Toolbar with panel drop down selector is ugly when vertical, but it's doubled in menu and bindable.

Yes, So it's best to use it horizontally or not at all.

> The lock button could lock the toolbars too. Don't know if it should also lock panel sizes.

It's just for turning off the title bars to save the space, I don't think anything more makes much sense...

> I'm not sure that context menu for activating panels is intuitive. It takes little but still some skill to get it with screen full of widgets. Maybe it's worth own place in main menu.

That's done by Qt automatically. Maybe I will offer a "show everything" button.

> Looks like storing layouts doesn't work yet. Clicking layouts in menu also doesn't affect drop-down selector.

That's right, not done yet.

> Is menu, status and tool bars are part of saved layout? 

I was thinking about that and I thought it might make sense to do that.

> That way distraction free mode can be just another layout.

I was thinking about that too, but unfortunately a lot more happens when the mode is activated...
I have to re-implement it...

> Note root selector should be a separate panel instead of embedded into note list.

You mean the combobox? Yes, maybe. But it will not look good above the note list if the tag list or note subfolder list is left of it...

> Sub-folders panel sometimes goes fixed zero size. Need to investigate more what causes it. Maybe that also the building issue of mine.

I have to re-implement the turning on and off depending if it is enable in a note folder or not.

> Preview got some big empty horizontal scroll I don't remember it had.

Hm, can't see that. Could you please make a screenshot?

> Overall it's very cool, UI feels like "photoshop" for notes.

Thank you, it's quite some work. But I think it's one of your greatest ideas! The only think I hold against you is that you had it NOW and not before I had implemented the current layout managing and turning-on-and-off madness. :)

**Comment by pbek** [comment]
Workspace switching, adding, removing, renaming and a lot more works now...

**Comment by Maboroshy** [comment]
> What do you mean by that? Currently you are able to do everything the layout-checkboxes do and much more.

I mean that when top and bottm areas were enabled panel could be docked there having full screen width. But as I've written no panels do really benefit from being screen-wide so it's not really a missing feature.

> Have you turned it on with the proper checkbox? Theses checkboxes will vanish too.

The panel is there but it's fixed zero size. I'm almost sure that it's a building issue of mine since note editor is kind of sub-project.
> It's just for turning off the title bars to save the space, I don't think anything more makes much sense...

Quite true. I thought it was a KDE UI pattern but I was wrong.

> I was thinking about that too, but unfortunately a lot more happens when the mode is activated...
I have to re-implement it...

I forgot about "editor width" thing. I think distraction free still has to stay in "workspaces" concept for not getting into multiple view modes again. Maybe it'd be possible to turn on distraction free features for "workspace" with screen-wide editor panel of full-screen editor panel. If that's impossible maybe it can be a hardcoded "workspace".

> You mean the combobox? Yes, maybe. But it will not look good above the note list if the tag list or note subfolder list is left of it...

Could you make a dummy combox panel for the next build to try?

> Hm, can't see that. Could you please make a screenshot?

Looks like it was not the app but the note - defalut "Markdown Cheatsheet". False alarm. :grin:

> Thank you, it's quite some work. But I think it's one of your greatest ideas! The only think I hold against you is that you had it NOW and not before I had implemented the current layout managing and turning-on-and-off madness.

Sorry mate, but that's not entirely true. That's what I wrote about #175 in May:
 
> Don't know anything about layout Qt classes but Dolphin file manager being also Qt app manages it's panes the way I described. I have places pane left and information pane right. Toggling any of them extends file browser without extending other panes. This panes always stay the size I've set them.
On the other hand looks like Dolphin's panes are more like toolbars and QOwnNotes uses different kind of widgets for it's layout. Changing widget types is a hell of a job for sure. 

Now I understand that Dolphin use QDockWidget.

I'll test new build and post what I'll find.

**Comment by pbek** [comment]
> I mean that when top and bottm areas were enabled panel could be docked there having full screen width. But as I've written no panels do really benefit from being screen-wide so it's not really a missing feature.

Those areas aren't disabled.

> The panel is there but it's fixed zero size. I'm almost sure that it's a building issue of mine since note editor is kind of sub-project.

Strange, I've no idea what could have gone wrong...

> Could you make a dummy combox panel for the next build to try?

I already had it on top of the note search line edit, and it didn't look good because the search lines weren't aligned any more.

> Sorry mate, but that's not entirely true. That's what I wrote about #175 in May:

We were talking about panes and not about QDockWidgets, they haven't crossed my mind... :)

> I'll test new build and post what I'll find.

The workspace switching menu entries crash on me sometimes (haven't found out how to fix that yet), but the combo box should work already.

Thanks a lot for your feedback!

**Comment by Maboroshy** [comment]
I've found menu entries issue too.

Also there's a rename entry in menu but no corresponding toolbar button.

Navigation panel is the only one having a title, so it's double title in unlocked mode. Not sure if it needs the title while other panels don't.

Maybe it's worth making a "workspaces" list panel to choose "workspace" with one click. The good thing about free layout is that there can be extra panels to choose from.

The distraction free mode opened up navigation panel full screen. I knew it isn't ready yet but still was surprised.

I've managed to make note edit panel work, so there's no issue with it.

I've also managed to make a panel below and screen-wide by moving all other panel above it one by one. And that made empty space appear again. But it was easy to fill it with some panel and all was good again. Since I was trying quite hard to get it and it doesn't break layout behaviour I don't see it as a bug.

After I enabled status bar I clearly saw different bottom margins for two lower panels. I checked that it wasn't for one panel type only but any panel put to that corner. After I made lower panel screen-wide and again put two-three panels there the margins were the same and I couldn't recreate the first layout. And I've tried hard.

The note tag panel have fixed height when it's unlocked but can be adjusted when it's locked for the height of it's now hidden title.

Apart from few missing pieces and some toolbar and menu arrangements still to be done it works very good and I have to try really hard to find some tiny glitches.

The one thing I wanted to save from current layout engine is a key shortcut for switching editor and preview turning it into a fast switch between two defined layouts. But it's a lot of heavy GUI to configure so it's overkill to implement. I can easily make it externally by shell-script. But think if there's a need for script-able workspace control logic that could be binded to custom actions.

**Comment by pbek** [comment]
> Also there's a rename entry in menu but no corresponding toolbar button.

I left it out on purpose. Do you thing we need a toolbar button for this?

> Navigation panel is the only one having a title, so it's double title in unlocked mode. Not sure if it needs the title while other panels don't.

I think it's not clear what it does if it doesn't have its column header.

Maybe it's worth making a "workspaces" list panel to choose "workspace" with one click. The good thing about free layout is that there can be extra panels to choose from.

> The distraction free mode opened up navigation panel full screen. I knew it isn't ready yet but still was surprised.

DFM is still on my todo list

> I've managed to make note edit panel work, so there's no issue with it.

great!

> I've also managed to make a panel below and screen-wide by moving all other panel above it one by one. And that made empty space appear again. But it was easy to fill it with some panel and all was good again. Since I was trying quite hard to get it and it doesn't break layout behaviour I don't see it as a bug.

Yes, it's not easy to get stuff down there.

> The note tag panel have fixed height when it's unlocked but can be adjusted when it's locked for the height of it's now hidden title.

It has a fixed max-height. That was the only way where I managed to force an initial height on it. I dislike that...

> Apart from few missing pieces and some toolbar and menu arrangements still to be done it works very good and I have to try really hard to find some tiny glitches.

I found a lot of glitches in OS X (as usual for OS X)... :/

> The one thing I wanted to save from current layout engine is a key shortcut for switching editor and preview turning it into a fast switch between two defined layouts. 

That's also on my todo list, but I'm not sure yet what to implement...
Should I create a hardcoded toggle between the first two workspaces?
Or make switching panels scriptable (a command for reading the current workspace and one command for setting an other workspace)? Any suggestions?

**Comment by pbek** [comment]
> The one thing I wanted to save from current layout engine is a key shortcut for switching editor and preview turning it into a fast switch between two defined layouts.

I think I will make a menu entry for accessing the last workspace, that would simulate toggling.

**Comment by Maboroshy** [comment]
> I left it out on purpose. Do you thing we need a toolbar button for this?
A usual I've written many clever thoughts about logic of translating menu entries to toolbar. But I think we must go "user control" route to the end. I've found [this](https://github.com/mbasaglia/Qt-Toolbar-Editor), it's quite old but maybe there is some ideas to borrow. There must be some toolbar editor laying around, it's essential, every KDE app has it. I still can't believe it's not a basic Qt functionality. They made this crazy docking thing and couldn't make toolbar editor..?

> It has a fixed max-height. That was the only way where I managed to force an initial height on it. I dislike that...

Maybe it's possible to set same size as minimum, so it would have fixed height.

> I think I will make a menu entry for accessing the last workspace, that would simulate toggling.

That's a simple and very elegant solution. I haven't even thought in that direction.

>Or make switching panels scriptable (a command for reading the current workspace and one command for setting an other workspace)? Any suggestions?

Nothing to add. Check, set and any basic logic user want between them with a bindings to custom actions. Not sure even these needed, not for me at least. Maybe you'd better wait for a feature request.

**Comment by Maboroshy** [comment]
Some more thoughts:
https://forum.qt.io/topic/32968/ui-customizable-toolbar
https://forum.qt.io/topic/32507/solved-qtoolbar-how-to-enable-the-user-to-re-move-icons/7

**Comment by pbek** [comment]
> toolbar editor

thank you, I will take a look at it

> Maybe it's possible to set same size as minimum, so it would have fixed height.

I don't want it fixed at all, because the sizes vary dramatically between desktop environments and operating systems

Meanwhile the DFM should work, the crashes are fixed, the old toggle code is gone along with the menu entries and a new button for switching to the previous workspace is implemented

**Comment by Maboroshy** [comment]
DFM is quite unstable. I'll investigate more and post what I'll find.

**Comment by pbek** [comment]
## 16.10.2
- all **panels** are now **dockable**
    - if you turn off panel locking you can **rearrange panels** as
      you like, they can even **float** or be turned off
    - there is a button to show all panels in case you lost some
        - you can also right click on the toolbar to turn on and off
          panels individually
    - you can create, remove and rename different **workspaces** and 
      switch between them
    - there is a button to **switch between the last two workspaces**
      for example to toggle between edit and preview if you don't want
      to show both panels
    - as a consequence of the new workspace feature the panel visibility
      checkboxes and the different panel placement settings were removed

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
I was just going to say that last builds were good enough to use "in production" and here it is! 

I've just set it up for me and all looking good.

DFM bug when no edit panel enabled is still there though. And I'm still pushing for having note folder combox as a separate panel! Or maybe note folder list panel as an additional one.

**Comment by pbek** [comment]
Thank you for the feedback, I've found some other issues...

> DFM bug when no edit panel enabled is still there though

thank you, I didn't know about that one

> And I'm still pushing for having note folder combox as a separate panel! 

but where should that panel go without harming the default look and feel?
currently that combobox can also be turned off and will be shown when the shortcut is pressed...

**Comment by Maboroshy** [comment]
As a separate panel it'd go where the user wants it and that is above sub-folders panel for me. The old school guys can place it above note list as it's now. 

It can be turned off, but not much choice if you want it on.

**Comment by michael-rowe** [comment]
Just wanted to say that I love the new dockable panels. I haven't come across any problems so far. Thanks for this update.

**Comment by pbek** [comment]
Thank you for your feedback @michael-rowe, I've already found and fixed some issues I found for the next releases... But there are still some more. ;)

**Comment by pbek** [comment]
## 16.10.3
- fixed a problem when the note edit panel was hidden before entering
  the distraction free mode
- fixed a problem with the restoring of the last workspace correctly
  when starting the app maximized
- the note folder combobox and the note search line edit now have their
  own movable panels
    - as a consequence the `Show note folders in main area` checkbox in
      the interface settings was removed
    - if the note folder combobox was hidden while the `Select note folder`
      shortcut in the main menu was pressed the panel will be hidden
      again after the combobox was closed
    - you have to move the two new panels to their proper places if you
      have already used version 16.10.2
- decreased the possible minimal height of the note tag panel

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
There are some minor issues.

I have two workspaces: one with note folder combox, note list panel, note sub-folder panel and note editor and the other with same but render instead of editor. All at the same places.

When I switch between them, no mater which way, combox gets focus (becomes blue) on the render workspace. It works as usual for editor workspace (no focus on switch) though.

When I switched to the folder that has sub-folders disabled in options editor workspace had sub-folder panel gone with empty space on it's place. But when I switched to render workspace there were sub-folders of a previous folder. 

The app saves sub-folder panel to workspace and disables it only on folder change event in that workspace. Using refresh key solves the issue so maybe you could make hook for a force refresh somewhere where it'd cause less pain.

**Comment by pbek** [comment]
I'm not sure what you are talking about and if you are talking about one thing or multiple. :) The subfolder panel will be hidden if subfolders are turned off for the current note folder.

**Comment by pbek** [comment]
I think I still fail to make sense of your words... So what is the focus issue? You are loosing focus of the current widget that has focus when you are switching to an other workspace?

And what is the issue with the subfolder panel?

**Comment by pbek** [comment]
I now already fixed the restoring of the focus after switching workspaces.

**Comment by pbek** [comment]
@Maboroshy but I still don't know what issue you had with the subfolder panel. ;)

**Comment by Maboroshy** [comment]
1. Add two folders, turn sub-folders mode on for the first one.
2. Make two workspaces with sub-folder panel.
3. You have two workspaces with the same first folder active. Sub-folder panel is on on both.
4. Choose second folder at one workspace, the panel will be gone.
5. Go to second workspace. The second folder is active but the panel will be there with sub-folders of the first folder. 
6. Press refresh and the panel will be gone as it should.

**Comment by pbek** [comment]
So in one sentence: The subfolder panel is not hidden when switching workspaces if subfolders are turned off for the note folder. Is that correct?

**Comment by Maboroshy** [comment]
Mostly. It will be and stay hidden if you refresh the workspace.

**Comment by pbek** [comment]
from the change log

## 16.10.4
- fixed the restoring of the focus after switching workspaces
- the log dialog is now a dockable panel that can be placed everywhere
- fixed a problem with showing the title bar of floating panels after
  application start
- fixed a problem where the note folder select box was hidden
- the subfolder dock widget is now turned on or off according to whether
  the subfolders are enabled or not when the workspaces are switched

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
All good for me.

**Comment by pbek** [comment]
Thank you for testing and reporting! I can assure you it was a lot of work. :) But you were my top-most driving factor to get me going doing it. 😸

**Comment by danielsanfr** [comment]
I just upgraded and noticed it was removed the option to switch between edit mode and preview mode. For me this was a major downgrade :-1:... I do not like having to keep both views ever!

I would suggest doing something like this: [Typora](http://www.typora.io/). I am willing to help the development, if necessary.

**Comment by pbek** [comment]
@danielsanfr, you can simulate that behavior.
From the changelog for 16.10.2:

- there is a button to switch between the last two workspaces for example to toggle between edit and preview if you don't want to show both panels

It even has the same default shortcut.

**Comment by danielsanfr** [comment]
You're right. The problem was that was not explicit how to do this for me.

But now I got it, thank you very much for your help and for developing this application!

I think to do something like Typora the editor would be amazing!

**Comment by pbek** [comment]
I'm glad it worked out for you. 

> I think to do something like Typora the editor would be amazing!

Can you please describe what "do something like" is for you? :)

**Comment by pbek** [comment]
@Maboroshy, as usual your wish was my command:

## 16.10.6
- the **buttons** in the **toolbars** can now be **customized**
  (for [Issue #343](https://github.com/pbek/QOwnNotes/issues/343))
    - there is a new `Toolbars` pane in the settings to add buttons from
      the main menu to toolbars, move buttons around or remove buttons
    - you can as well **add custom toolbars**
    - if you have messed the toolbars up you can also reset the toolbars
      to the default

It was quite some work. ;)

**Comment by pbek** [comment]
there are still some issues, like that the window toolbar can't be modified because of the magic that is happening there

**Comment by pbek** [comment]
@Maboroshy there now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment]
Very cool! Looks very close to what KDE guys have. There's even a custom actions buttons there! And I was just thinking about separators for bash-note toolbar I've made. I'll give it a try and post what I find.

By the way, you only take thoughtful and proved "wishes" as commands, I've tried some stupid ones and that didn't work. :smile:

**Comment by pbek** [comment]
I took extra time to make the custom actions in custom toolbars work... ;)

> By the way, you only take thoughtful and proved "wishes" as commands, I've tried some stupid ones and that didn't work.

lol, I'm glad that the vast majority of your thoughts are thoughtful :)

**Comment by Maboroshy** [comment]
And my first try was to extend custom actions toolbar with some buttons. Reloaded the script and it got reset. :anguished:

**Comment by pbek** [comment]
That toolbar gets reloaded along with the script engine (naturally). Better use a custom toolbar and add your custom actions.

**Comment by Maboroshy** [comment]
Ok, here's what I've found after first pass. Since that's the first time I paid that much attention to toolbars which I have mostly off, I may have added some things beyond the feature scope.

Settings UI:
- Buttons in the middle are very wide and far form each other. That means big distances for eyes and mouse without any gain. 
- Available and toolbar action columns are not labelled which makes new user confused for a few moments. Same with insert/remove buttons.
- All the above = take a look at KDE UI for that, like the one in Dolphin.
- The folder names from note folder section can be added but they won't appear on toolbar. Similar workspaces name work. 
- Folder names in the section tend to multiply. Looks a change of workspace causes it.
- You can't assign icon to a "name". I do understand that change icon UI is a hell for cross-platform app though. Good thing I know of endless Unicode tables. But please add icon to "Select note folder" item! It's the only "normal" item which has none.
- Separator icon is little weird. Maybe it'd be better same as on the list - "--- Separator ---".

Appearance:
- Some buttons, specifically the ones with drop-down like folders and workspaces are removed when app language (localization) is changed.
- Lock panels button is "pressed" when panels are locked. Pretty logical. But while the panels are mostly locked seeing "pressed" button all the time is distracting. Maybe it'd better be "Unlock panels" button.
- Reload folder and reload scripting engine have the same icon. I propose change the scripting one to `step_object_LinearMotor.svg' from the Breeze set.
- Maybe it's time to ditch quite toolbar since it was there for a rare special purpose and you now have that covered.

Custom actions:
- Reloading scripts don't reload toolbars, so dead custom action buttons will still be on toolbar.
- When you've thought that that's how it should be, app restart will remove all custom action buttons from toolbar. And they won't come back when you'll add the script back.
- When tinkering with custom actions their toolbar like to pop-up on active workspace even when it was disabled before. Maybe it should always be but be empty when there's no actions.

But overall very good and very useful. Going to start using toolbar at last! And less "I want new button" issues for you! Complete user control.

**Comment by pbek** [comment]
Thank you for your elaborative feedback, I hope anyone else beside you spots one or two of these things. :) Could you please open a new issue with all this...

**Comment by pbek** [comment]
@Maboroshy thank you (topic moved to #368)
