### ISSUE TITLE
ToDo entries not loaded

### ISSUE THREAD

**Issue by Olhur** [pbek/QOwnNotes#35]
Hi!
I have encountered a bug after setting up QOwnNotes with todolist. Although everything is connected correctly and calendars are found, opening the todolist results in not showing any entries even after reloading. In console, every entry is accompanied with this log:
```
QSqlQuery::value: unknown field name 'sort_priority'
store :  QSqlError("", "Parameter count mismatch", "")
```
Do you have any idea what is wrong with either an app or my ownCloud setup?

Best regards!
Filip

**Comment by pbek** [comment]
Thanks a lot for the report, @Olhur !
That really is a bug that crept in with some refactoring work.
It should now be fixed in version 0.83. You should be able to get the new version in a view minutes.

Could you be so kind to report if everythings works fine when you get the new version.

Cheers, Patrizio

**Comment by pbek** [comment]
You may need to reinitialize the database in the settings dialog.

**Comment by Olhur** [comment]
Yes, now it works like a charm. Thanks a lot!

**Comment by pbek** [comment]
Thanks for the check and thanks again for the report!
