### ISSUE TITLE
Improving Accessibility with Screen Readers

### ISSUE THREAD

**Issue by alshmasi** [pbek/QOwnNotes#352]
Hello!
The app is a grate and convenient way to sort notes, which is something I need a lot these days.
However, it has some accessibility issues with screen readers, such as NVDA.
The most important issues in that matter is accessing to edit fields, correct labeling, and accessing the notes list.
This app will be very important to me in the coming university year, and I hope that you take this problem in consideration to solve in the next update.

Giving this opportunity to blinds is a key factor for a successful and productive working experience, and it will put your application on top of the others in that field.
Best regards!

**Comment by alshmasi** [comment]
Thanks for the fast response.
I'm not a programmer, but from an end-user experience, the screen reader 
doesn't read anything when I navigate inside the edit fields using the 
keyboard.
When pressing tap in the main window, sometimes the screen reader 
doesn't say anything, which means that there are some elements that 
can't be read.
Navigation in the menu bar is also hard, to avoid any problems I have to 
switch to another window, then switch back to the program window again.
In settings, the defining shortcuts section is also hard to navigate 
through, since the screen reader only speaks the short key, not the 
action for that short key.
Those are all the problems I found until now. Sorry for not listing some 
possible solutions for them, because I don't have the experience to do 
so, but I'm ready to test the app and give you a detailed feedback if 
you want.

**Comment by pbek** [comment]
Thank you for your explanation. I will see if / what can be done.

**Comment by pbek** [comment]
I've downloaded and installed NVDA under Windows and it reads the text from menu. It also reads from read-only text edits like the debug log. It doesn't read from the note edit, but as far as I see NVDA generally doesn't read from text edits.

Unfortunately I have no idea how NVDA decides what to read and what not and I haven't found any information on it on their website.

Do you have any additional technical informations?

> the screen reader doesn't read anything when I navigate inside the edit fields using the
keyboard

for me it read the text I was typing

> When pressing tap in the main window, sometimes the screen reader
doesn't say anything, which means that there are some elements that
can't be read.

Which elements for example?

> In settings, the defining shortcuts section is also hard to navigate
through, since the screen reader only speaks the short key, not the
action for that short key.

I have no idea how to improve on that neither, since I haven't found any documentation on what NVDA is actually doing to get the text.

**Comment by pbek** [comment]
I will close this issue until there is more information.
