### ISSUE TITLE
Edit text directly in WYSIWYG? Copy/Paste-WYSIWYG import does not work. 

### ISSUE THREAD

**Issue by Waldi-X** [pbek/QOwnNotes#375]
I'm new user because @nextcloud. 
Could I edit text directly in WYSIWYG? Copy/Paste-WYSIWYG import does not work. 
Example Copy and Paste. It shows not what I want.
![20161027-qownnotes-no_wysiwyg-example](https://cloud.githubusercontent.com/assets/23096177/19762422/2c79c09e-9c3a-11e6-94f6-3812993941f7.jpg)

**Comment by pbek** [comment]
> Could I edit text directly in WYSIWYG?

No, I'm sorry. Please see #192.

> Copy/Paste-WYSIWYG import does not work. 

Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by pbek** [comment]
On a side note: QOwnNotes uses markdown! See <https://github.com/pbek/QOwnNotes/blob/develop/src/demonotes/Markdown%20Cheatsheet.md> for more information on the syntax.

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by metal450** [comment]
I'm pretty sure what he's referring to is pasting formatted text into QOwnNotes, & having it retain the formatting.  For instance, if you copy text from a browser & paste it in Word, the formatting will (generally) be preserved. If you copy from Word & paste in OneNote, or from an Outlook e-mail & into a Wordpress composer, and so on and so forth.  This makes it extremely easy to move pre-formatted text around & quickly save notes without "losing" some context that's often contained in the formatting.   When he says "copy-paste does not work," I believe he's referring to formatting.

I'm personally trying to find an alternative to move away from OneNote, but this is one "blocking" issue for many of the open-source notes editors for me.  Though Markdown is great & has its uses, sometimes you do want formatting to be preserved, like in most "mainstream" richtext editors :)

**Comment by pbek** [comment]
@metal450, are you referring to to the already existing *Paste html or media* feature?

**Comment by pbek** [comment]
@metal450, are you referring to to the already existing *Paste html or media* feature?

**Comment by metal450** [comment]
Yes!! Something like that :) I didn't find it because it didn't respond to the standard Control-V shortcut ;)  

However, although that does seem to get some of the formatting, unfortunately it still does come out quite vastly different from copying/pasting between the aforementioned editors.  For instance, when pasting from OneNote to QOwnNotes, although bold, italic, & underline worked - spacing & alignment was very far off, fonts often had issues (i.e. a Symbol font at the start of a line, like an arrow, would cause the whole rest of the line to be "symbol" & unreadable in the paste), colors would also sometimes "bleed" from where they start to the end of a line (i.e. context-highlighted code pasted into it would, at some point in a line, start a color that continued to the end of that line), etc.  Pasting from Word had almost unrecognizable alignment/spacing, and there was some non-interpreted HTML in the paste (i.e. rather than colored text, it shows directly the <span> tags).  And so on :)

**Comment by pbek** [comment]
> Yes!! Something like that :) I didn't find it because it didn't respond to the standard Control-V shortcut ;)

It isn't supposed to. QOwnNotes is a plain text notepad.

> spacing & alignment was very far off, 

markdown doesn't support such things

>  Pasting from Word had almost unrecognizable 

above mentioned keyboard shortcut is just trying to convert the (mostly abysmal) html it gets to markdown

**Comment by pbek** [comment]
You can always use http://docs.qownnotes.org/en/develop/scripting/README.html#accessing-the-clipboard to write your own pasting method.

**Comment by pbek** [comment]
You could even use some fancy javascript library to do the conversion to markdown. I'm expecting a pull request at http://github.com/qownnotes/scripts if you come up with something. ;)

**Comment by metal450** [comment]
>>markdown doesn't support such things [...] It isn't supposed to. QOwnNotes is a plain text notepad.

Ah, gotcha.  Yeah, I was more hoping for / looking for a "replacement" for OneNote which I could self-host, though I've got an enormous existing quantity of notes in OneNote, which makes use of full richtext formatting.  I've looked at quite a few options & QOwnNotes seemed to be the most mature & full-featured, but if it doesn't support richtext (or equivalently, html) notes, I guess it wouldn't work as a replacement in my personal case unfortunately :/

Thanks for the super quick replies tho! :)

>> why not export to a compatible external application and then import to QOwnNotes? It is an extra step but it gets the work done.

...But wait, doesn't it not support this type of formatting (per pbek's replies above)?

**Comment by pbek** [comment]
Yes, QOwnNotes was not meant for html notes...

**Comment by metal450** [comment]
I actually had tried out Joplin too, & it appeared to behave the same (i.e. when pasting formatted text, formatting was lost).  If you say it does support HTML though, perhaps I'll have another look & post over at their forums.

In any case, my +1 for QOwnNotes stands :)

**Comment by metal450** [comment]
I understand. I wasn't looking for a markdown editor in particular, just a OneNote/Evernote alternative. It just so happens that many of the self-hosted options seem to use Markdown rather than HTML, which leads to compatibility issues such as these - though for my purposes, the underlying text format implementation is somewhat incidental; I was simply looking for somewhere I could migrate my large library of OneNote notes that's 1) Self-hosted, 2) Supports standard richtext formatting (one way or another).  I understand that the markdown-based solutions may ultimately not be suitable, I just thought I'd reach out & ask since I saw this thread posted here, & QOwnNotes otherwise seemed to be the best option I'd found ;)

**Comment by subi54** [comment]
I'm in the same boat as you. I have used OneNote since it was introduced. Loved the thing. Never got into Evernote because of it.
But the UWP app or whatever they call it is such a mess. It could never really replace the traditional 32-64bit apps.

I tried around a lot of stuff, just can't find the one, you know. The best thing about QOwnNotes is, you can sync the .md files folder and have iA Writer or something to edit on mobile.

But .md files are bad for long notes, outlines and such.

I'm using [Dynalist](https://Dynalist.io), which is an outliner for most part. Been using for more than a year now, quite satisfied with it. Haven't actually used OneNote that much with that around.

Switched all long notes to Joplin. Still .md files but I have the switch to top, bottom and ToC in long files with the id & a href tags. So efficient that is.

**Comment by metal450** [comment]
Cool, thanks for the ideas.

**Comment by pbek** [comment]
I like simple markdown files because I will be able to use them my whole life, regardless of the software to edit them... :)

**Comment by metal450** [comment]
Sure, there are benefits to each approach.  There's something to be said for the simplicity of Markdown & the fact that you can open it in any "plaintext" editor.  Similarly, as most "mainstream" editors use WYSIWYG+HTML/richtext, there's also something to be said for that side of compatibility :)  Markdown is great when you want to view/edit your notes with pure plaintext software; but HTML is cross-compatible with OneNote/Evernote/Word/Browsers/most consumer-facing document applications.  As I'm personally starting with an existing repository of documents in these common formats (as I'd imagine many potential users might), losing all the existing formatting isn't really a viable option, unfortunately.

**Comment by metal450** [comment]
Those other apps (with the exception of browsers) don't technically *store* as html either - they have their own native binary file formats.  My discussion wasn't related to the specific underlying file format (could be stored as html, richtext, or any other suitable format), but simply to being able to exchange the same degree of formatted text between those various editors.  As for whether it's actually stored as HTML vs another format not technically designed to be presentation layer...that's just an implementation detail.  HTML seems to be a fairly common choice as it's renderable by a huge variety of softwares, but it's certainly not the only one.

**Comment by pbek** [comment]
Proprietary formats are even more of a no-go for me. :smile: 
But even an app like Joplin who supposedly uses Markdown for notes does it in a manner where you couldn't use them outside of Joplin easily...

**Comment by metal450** [comment]
It could always be offered as a user choice.

*Store notes as plaintext = not compatible with the full variety of formatting offered by other editors, but files can be opened with any plaintext editor & are 100% portable.
*Store notes as (any richtext-capable format you deem most appropriate) = compatible with full variety of formatting offered by other editors, but files may be less portable.

Again, different strokes for different folks.  Perhaps in your case, the top criteria are absolute portability, not using a proprietary format (even if it's widely supported), and not using a presentation format for storage.  Perhaps in the case of others, the top criteria is richer formatting & they're not as concerned with storage format.

Again, I understand that it's unlikely to ever be supported.  I'm just trying to communicate that the priorities of "files must be plaintext" may not be correlate with *all* use-cases - a likely common example being users attempting to replace alternatives like OneNote & Evernote.
