### ISSUE TITLE
Add description for Syncthing/Resilio Sync

### ISSUE THREAD

**Issue by mvhconsult** [pbek/QOwnNotes#418]
It seems like only ownCloud is an option. But the very stable and fast Syncthing (or the commercial one Resilio Sync) are very good options as well. Just set up the sync directories and notes are synced at really fast speed.
Please add to docs, it will increases spread (especially with all the negative info on E**Note these days)

**Comment by pbek** [comment]
Thank you for your suggestion, but you can use whatever file-sync you want, it's almost impossible to add every method or tool. Although Syncthing is already mentioned...

> The notes are stored as plain text files and you can sync them with your ownCloud or Nextcloud sync client. Of course other software, like Dropbox, Syncthing, Seafile or BitTorrent Sync can be used too.

Some of them are already named on the QON webpage...
ownCloud / Nextcloud are the default because you can use the ownCloud notes app to edit your notes and QON offers additional support for oC / NC.

**Comment by mvhconsult** [comment]
The opening page here still states:

> The notes are stored as plain text files and are synced with ownCloud's/Nextcloud's file sync functionality. Of course other software, like Dropbox can be used too.

**Comment by pbek** [comment]
If you were talking about <https://github.com/pbek/QOwnNotes/blob/develop/README.md> and note the webpage you could simply edit it yourself and make a pull request... I now added a Syncthing link.
