### ISSUE TITLE
New note title should honour regional settings

### ISSUE THREAD

**Issue by mpodshivalin** [pbek/QOwnNotes#439]
When I press Command+T, date and time are inserted correctly according to my regional settings:

```
28.12.16 18:14
```

When I create a new note, date and time looks differently:

```
Note 2016-12-28T18.14.37
```

My idea is that it should always look the same, so in my case new note title should be

```
Note 28.12.2016 18:14:37
```

**Comment by pbek** [comment]
> Note 28.12.2016 18:14:37

I'm sorry, the date string is intentionally modified because the `:` is not very encouraged in a file name. ;)
But you can use what ever you like as note headline with a little script, see: <http://docs.qownnotes.org/en/develop/scripting/README.html#handlenewnoteheadlinehook>

Does that answer your question?

**Comment by pbek** [comment]
There also is a scripting hook to modify the file name alone and you can also create a custom action to write any text you like to your note (e.g. the current time in a custom format).
