### ISSUE TITLE
Integration with nextcloud / notes

### ISSUE THREAD

**Issue by erwinfrohsinn** [pbek/QOwnNotes#479]
Thanks for QOwnNotes - I just migrated by basket notes to QOwnNotes and I also use nextcloud.
I read here https://github.com/stefan-niedermann/nextcloud-notes/issues/2 that the nextcloud-notes project will support markdown. Will that mean that we will see the notes formatted in nextcloud-notes as they are in QOwnNotes?
Moreover, I'd find it helpful if development directions could be synced, e.g., that the QOwnNotes keywords could be transferred to nextcloud-notes. I know that I could have placed this request also on the nextcloud-notes side, but just to start discussion without redundancy, I placed it here.

**Comment by pbek** [comment]
QOwnNotes already supports markdown...
And I don't know about Nextcloud keywords, do you have more information or is this a feature request for Nextcloud notes?

**Comment by erwinfrohsinn** [comment]
QOwnNotes supports markdown, but nextcloud-notes doesn't (yet), and I wanted to understand, whether there will be need to modify something on the side of QOwnNotes, so that the markdown formatting as done in QOwnNotes will be visible in nextcloud-notes, as soon as they will support this (if it is not too early to answer that question).
I have not found keywords in nextcloud-notes, but since QOwnNotes has them, I'd like to see them in nextcloud-notes. That would be effort on both sides, but it would be useless for me to place a feature request to nextcloud-notes, if you wouldn't be willing to do a biddirectional synchronization of the keywords - That's why I started the discussion here. Thanks again!

**Comment by pbek** [comment]
> markdown formatting

I don't think there will be a problem, since there is a standard for most of the "formatting", there's nothing to worry and to discuss.

> keywords

I think we can only have a discussion about that if there actually are something like tags NC notes...
QON stores the tags and the link between a note text file and a tag in the `notes.sqlite` database for each note folder. Note sub-folders of that note folder are using above database from the root note folder.

Is there anything else on your heart or did I miss something?

**Comment by erwinfrohsinn** [comment]
No, thanks, your answer addressed my topics. Best Regards!

**Comment by pbek** [comment]
I will close this issue until there is more information.
