### ISSUE TITLE
Feature Request: Keyword recognition

### ISSUE THREAD

**Issue by stevenbuehner** [pbek/QOwnNotes#5]
Hi,
I really like this app. Is there any chance to add a keyword syntax to add keywords to every file or even to parts in the file.

For example like: I want to talk about [[my Keyword]] in a plain text...

**Comment by pbek** [comment]
Thank you for your praise and your suggestion. Keyword were already kind of on my mind. But since the ownCloud web app and the iOS app don't support keywords I don't really know what to do with them. So what are your thoughts?

**Comment by zocker22** [comment]
Mhh. Good question. I have see different general Classes and DB-Entries in Owncloud that implement basic tagging functionality. Although nobody has used it so far.

Here is what I tried so far:
- In the beginning I just added the keywords to my filename, commaseparated. But unfortunately the length of the filename has a maximum, which I already hit sometimes.
- Right now I add all my keywords commaseparated in the first line of my document, which makes it easy for any app to search or index, because the textfile can be read only partially. But for very long textfiles it would be nice to add keywords to a section or at a certain place of the text.
- Therefore another very easy and basic way would be to just write them in the textfile surrounded by special brackets to recognize them in the markup view or even in the list on the left side of your QownNotes app.

What have your thoughts ben so far?

**Comment by pbek** [comment]
To really make use of a tagging feature it would be nice if ownCloud notes would support it too...
And I guess I would have to reinvent the whole user interface of QOwnNotes and how everything works to make use of tagging. (For example to group notes by tag.)
Sooner than later I would have to start to store everything in a database instead of just using the plain text files...

**Comment by wexaadev** [comment]
i have suggestion 
we can create a lib ( xml file) like that
<ownnote>
    <note   name=""  date = ""  path = "" color ="" >
        <keywords   key1 =""   key2 = ""   key3 = ""  />
   </note>
</ownnote> 

if you want to keep the txt file its ok  , if not we can add a new element to lib <text> 
like that its easy to sync the lib with owncloud 
if its ok i can begin in creating the lib and classes for it

**Comment by pbek** [comment]
Do you also want to store the content of the note in this xml file or just meta data, like tags?

**Comment by pbek** [comment]
Because we will never be able to have one central database file for all the notes, this would be a mess to sync with ownCloud (or other sync clients) and break compatibility with ownCloud Notes and the mobile clients.

**Comment by wexaadev** [comment]
- PATH- DATE
  to be able to filter by folder or by date 
color also can be a label  for importance .
 we keep the text file i want just collect informations  and stored in xml lib  to do some filters in local  and at every sync we update automatically the lib .

**Comment by wexaadev** [comment]
and we link every note with the lib .
if we have a new sync and new files created outside of qownnote we notified that and we give option to user to create some tags for it.

**Comment by pbek** [comment]
I would be important do performance tests first... QOwnNotes already uses a in-memory sqlite database for metadata. As I once tried to store it on disk instead of memory and tested it with my 1000+ notes folder on an iMac with spinning disk I was pretty disappointed. It was unusable. :grin:

**Comment by pbek** [comment]
By public demand a tag implementation is currently in the works.

Each note folder will have its own database (with tags and their links to certain note files). The database is a sqlite file, that will be stored directly in the note folder.

I hope it will play together with syncing the database-file via ownCloud and with external changes of the database-file.

**Comment by pbek** [comment]
Version 1.3.7 with tagging support is now out. Can you please test it and report issues?

- you can turn on tagging with <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>T</kbd>
- tags and their associations to note files are stored in each note folder
  individually in a SQLite database
- if notes are renamed by QOwnNotes the tags will be moved to the renamed
  notes
- if notes are move to an other folder their associated tags are lost 
- <kbd>Alt</kbd> + <kbd>⇧</kbd> + <kbd>A</kbd> adds a new tag to a note

**Comment by pbek** [comment]
I am closing this issue until there is feedback.
