### ISSUE TITLE
git push probleme

### ISSUE THREAD

**Issue by wexaadev** [pbek/QOwnNotes#58]
hello
i want to contribute in your project but i have some problems.
i am already add  a  " new note dialog " to give option to user to name it , i test it ,work fine .
i am newbie in git , sow when i wan to push my modification to develop branch i got error 403 no permission .
i need your help.

i want to contribute this is my first , i have some features .

error

remote: Permission to pbek/QOwnNotes.git denied to wexaadev.
fatal: unable to access 'https://github.com/pbek/QOwnNotes.git/': The requested

information

i already change the url in my config from "https://github.com/pbek/QOwnNotes.git" to "ssh://git@github.com:pbek/QOwnNotes.git"

i clone with -b develop

**Comment by wexaadev** [comment]
![screenshot from 2016-02-05 12 28 04](https://cloud.githubusercontent.com/assets/15630598/12848854/2f05db64-cc14-11e5-8dd8-9aa54d0c08db.png)

**Comment by pbek** [comment]
Hi @wexaadev 

Thank you for your interest in contributing to QOwnNotes!

**About pushing to the repository**
You can't push to the repository directly. You have to fork the repository, there is a button for that here on GitHub. Then you can push to your fork and create a pull request for the repository you forked from.

**About your dialog**
When will this dialog be triggered?
Because you already can to create a note with a certain name by typing it in the search/new bar and pressing enter.
When there is no time for entering a name, you can press Ctrl+N to create a new note with a predefined name.
A “new note” dialog would be a bit redundant in my eyes.
What’s your view on this?

**Comment by wexaadev** [comment]
hi @pbek 
thank you now all its work fine 
about my dialog 
in my opinion i see is better to give option to user to name the note o keep the default name with date , with a dialog it s match easer  and to create communication between user and QOwnNotes  also in the future we can add some filter by names, by date by folder, some tags with color or names .

**Comment by pbek** [comment]
Currently you can rename your notes by editing the first line of your note. This will also result in a renaming of the note file. This behaviour is enforced by the ownCloud notes client (and the iOS and Android client) and thus also practiced in QOwnNotes.
So I still see no need for an other user interaction. :wink: You can press `Strg + Shift + F`, enter your note name and press `Enter` to create a note with a name.

Tags would be nice and also wished for in issue #5.
But as long as there are no tags in the ownCloud notes client it will be easy to implement them in QOwnNotes.

**Comment by wexaadev** [comment]
ok 
now changing in issue #5.
