### ISSUE TITLE
Update selected note when tag/sub-folder are changed

### ISSUE THREAD

**Issue by msbentley** [pbek/QOwnNotes#600]
A minor issue here - currently when selecting a new sub-folder or tag the note list is updated, but the note window contains the previously selected note (even when it is not a member of the selected folder and does not contain the selected tag). My preferred behaviour would be to select the "top" note in the filtered list... anyone else?

**Comment by pbek** [comment]
@Maboroshy, @derboblan your opinions?

**Comment by Maboroshy** [comment]
@msbentley has a point, but his proposal have a side effect.

Good UI should do what the user want. If it does something, that user has not asked for and does it for some time, the user start hating the app.

So what if the first note in sub-folder is some big note with many images. Each time the user will open that particular sub-folder the app will waste his time to load the note he didn't asked for. First he'll think "silly me, I should rename this note so it won't be the first". Next are "damn, I forgot to rename that note again", "not this sub-folder again", "it's not my fault, this app is too slow". 

But the app is fast really. To resolve the issue and to show user that app is fast we should load an empty place-holder. What most apps show you when you open new window? Last opened file? First in the list file? Empty place-holder. That's an expected behaviour. When the user opens a sub-folder no note is selected, so there's no reason to show him some new note until he asks for it.

Next question is what's more useful to show the user: last opened note, that was asked by the user and is there fully loaded, or empty place-holder? Some text that user asked or nothing. I don't think nothing is any better. Loading nothing still takes more time than leaving current note.

So I say leave it as it is now. I never felt out of typical UI patterns to me.

**Comment by msbentley** [comment]
I appreciate your points - it may be because the other note apps I've used in the past explicitly focus "a note" (typically the top/bottom of the list, as sorted by user preference) when selecting a tag/notebook. So I keep being confused that I have explicitly asked to see only notes from a given folder, but am seeing something else. Anyway, it's a minor thing - I can try to reprogram my brain rather than having to reprogram QON ;)

**Comment by pbek** [comment]
@Maboroshy has good points (that I never would have come up with, that's the reason he's the man for such questions). :smile: :+1: I guess we will leave it be for now.
