### ISSUE TITLE
Remote (http://) images preview

### ISSUE THREAD

**Issue by Flashwalker** [pbek/QOwnNotes#609]
Does QOwnNotes has ability to preview remote images with http:// source?

**Comment by pbek** [comment]
I'm sorry, the preview doesn't load external sources.

**Comment by sancho-one** [comment]
Are you planning to add this feature in the future? It's not critical, but it would be nice because currently one can view notes with images inserted by QOwnNotes only in QOwnNotes. As for me, for instance, I use iA Writer which in contrast doesn't show "local" images by QOwnNotes, but shows remote images. This situation stops me from adding images into my notes as I guess otherwise after some time I'll finish wish a mixture of remote and local images, partially opened in QOwnNotes and partially in iA Writer. What do you suggest, @pbek? Maybe, you'll share your personal method dealing with images. I guess you work with your own notes not only on you laptop, don't you? ;)

**Comment by pbek** [comment]
This will not be possible with the currently used QTextEdit for the preview. It will work when in some future a fully fledged browser will be used for the preview (with all it's disadvantages and advantages)...

I usually don't use images. I normally don't even use the preview. :)

**Comment by sancho-one** [comment]
Thank you for the reply!

On Mon, Sep 25, 2017 at 11:26 PM, Patrizio Bekerle <notifications@github.com
