### ISSUE TITLE
Syntax highlighting inside Code Blocks

### ISSUE THREAD

**Issue by mhoeher** [pbek/QOwnNotes#666]
I often insert code snippets (config file excepts, bash scripts but also snippets of other programming languages) into notes. This already works by using code blocks (enclosed in triple ticks).

Some implementations of Markdown (e.g. GitHub and GitLab) allow you to specify the language a snippet is written in, e.g.:

    ```bash
    cd "$FOO"
    mkdir ./{bar,baz}
    touch ./*/stamp
    ```

Such implementations usually also will highlight the contained code snippets accordingly, e.g. GitHub usually will highlight some built-in command names for Bash; for other languages, reserved keywords are highlighted and so on.

It would cool if QOwnNotes could also provide such code highlighting:

* At least in the preview pane.
* And even better: Maybe directly in the code editor :-)

**Comment by pbek** [comment]
Thank you for your suggestion, but I guess this currently will not happen, since it someone would need to write it by hand and integrate it into the current highlighter...

And for the preview please see: #621
But of course you could try to play around with the script <https://github.com/qownnotes/scripts/tree/master/markdown-it> or implement your own preview code generator with it. (I'd love to hear if you was able to do that.)

**Comment by mhoeher** [comment]
The script you pointed to would affect the preview only, right? I will definitely play around a bit with it. I guess one could integrate any MD2HTML renderer if it can be wrapped into such a script, right?

**Comment by pbek** [comment]
> The script you pointed to would affect the preview only, right? 

right

> I will definitely play around a bit with it. I guess one could integrate any MD2HTML renderer if it can be wrapped into such a script, right?

right, if it's written in JS
