### ISSUE TITLE
Semi-support for other files than markdown

### ISSUE THREAD

**Issue by little-curiosity** [pbek/QOwnNotes#688]
Hi,
one thing that still keeps me from switching to QOwnNotes completely is the support of HTML file and other file types, especially PDF. I usually clip a web page and then highlight it for my reference, for me it is not possible with Markdown format now (please let me know if there is an easy way to do that). For other file types, would it be an idea that QOwnNotes can display it in the list and has an option to open it natively in other program? I'm organizing my notes together with other related files (mostly PDF and images) in separate folders. QOwnNotes does not even need to display or preview it in the program, as long as I can see the file in the list of notes, it would be perfect for me to open it outside of QOwnNotes using some keyboard shortcuts (Ctrl-Shift-O for instance).
Best,
LC

**Comment by pbek** [comment]
QOwnNotes can only (and possibly will only be able to) handle Markdown files. But you can use any file-extension you like and also can turn off the highlighting.
If you want to work with HTML files it would be better to use something else. :)

Does that answer your question?

**Comment by bepolymathe** [comment]
I'am not sure to understand exactly your question but if you insert an attachment file (Ctl+Shift+e) and select a PDF file, it include a link in Qownnotes. You just have to use Ctl+right click to open this file in the external application by defaut for PDF file.

**Comment by Maboroshy** [comment]
Inbox script turns all non-.md files to notes that contain image or link to that file. 

It can be developed further so it would create a note that would run external application on opening or on custom action (toolbar button, key-shortcut).

Alternatively, the user can add non-note file types files as custom note extension, as @pbek proposed.
The script can run external application when "notes" with custom extension opened. But QON would still open them itself as a text, and that can take some time with something as big as a .pdf.

For me the best solution is the one that inbox script does. Maybe I should make it work like that for whole note folder, rather than for specific sub-folder.

**Comment by little-curiosity** [comment]
Thanks for all your replies. Some clarifications from my side:
- @pbek: What I meant by highlighting is not the code highlighting but traditional text highlighting. My workflow for collecting data from the web is that whenever I need to save a web page or part of it, I use a browser extension called tagspaces from the program with the same name to save the file as a single html files, together with images and text. If I want to highlight some important parts of that save web page, I can use a highlightert function of tagspaces to highlight that part, I guess technically it changed the background of those texts to yellow or whatever color I chose for the highlighting. As far as I know, markdown does not support the highlight function, or maybe you need to introduce some html code there. What I wanted to ask is that if possible, could you implement that kind of function to the markdown editor so that when a note is rendered, the highlighted part can be.
If you are not planning to support rendering HTML files (even just for previewing), I understand and can live with that.
- @bepolymathe: thanks for reminding me of the insert attachment function. My only concern is that when inserting a file, QON will change the filename and move it to the media folder. Because of that, I'm afraid that one day if QON is stopped developing, the file:// URL in the md note will not work anymore in a different note program. What I would prefer is to have an option that QON will not rename the file, just keep its original name and either can move the file to a subfolder called "attachment" or "media" in the folder that contains the linked note. By that way, even if I use any file manager program on any OS to browse my note folder, I still can know which external files belong to which notes. My issues with other note programs is that even though the notes are stored, say, in json format, it's always a risk that I will lose access to my notes if the program stops working/being developed and there is probably not an easy way to migrate to other program when notes and attachments are stored in that way. I would like to have my notes and related files stored in a transparent hierarchical way so that in worst case, I still can use a file manager to organize my notes.
-  @Maboroshy: Inbox script looks interesting and I like the way it does not change the filename, even though it looks like that the script still moves the file to a common "attachment" folder. Also for me, it is not very straightforward to use as I need to open first the file manager to copy the files to the Inbox folder, then come back to QON and use the script to process the files. As I said in my first comment, I don't even need QON to open or render non-text files such as PDF files or images, I just need QON to display the files as items in the note folder, along with the note files and to allow me open those files externally using keyboard shortcut.
Sorry for the long text but I like QON as a note program a lot because of its flexible and clean GUI as long as its rich functions and very active development from pbek.

**Comment by pbek** [comment]
@little-curiosity you can only "highlight" text by using markdown, like `*emphasis*`...

**Comment by bepolymathe** [comment]
Let's start with the beginning.

> Sorry for the long text but I like QON as a note program a lot because of its flexible and clean GUI as long as its rich functions and very active development from pbek.

Yes me too ! Thanks to @pbek for all and to @Maboroshy to actively scripting.

> I'm afraid that one day if QON is stopped developing, the file:// URL in the md note will not work anymore in a different note program.

But are you sure that the structure of your notes folder will not change? That your OS will not evolve? For the rest, @pbek is young and healthy (I hope!);)

> What I would prefer is to have an option that QON will not rename the file, just keep its original name and either can move the file to a subfolder called "attachment" or "media" in the folder that contains the linked note. 

I think this is the condition for not having duplicates ... but I think it would be simpler to have a logic behaviour (for me) like: file of notes + attachment and media. Only one main folder and two files of "external elements" (text and images). 

For @Maboroshy 
> Maybe I should make it work like that for whole note folder, rather than for specific sub-folder.

I completely agree with that.

have a good evening

**Comment by Maboroshy** [comment]
@little-curiosity 
You want to use QON with the file structure what is different to what the app use. Implementing opening non-text files from the note list is possible. @pbek could make a scripting hook that would stop the notes from rendering, if he is convinced. Or you machine would eat some CPU cycles if @pbek is not convinced. Don't know if using `noteToMarkdownHtmlHook` to output empty html to render will make the desired effect. I could make a geeky custom action script to open note list item based on it's extension. 

But you will always be restricted by using the app in an awkward way. So I suggest using it as it's made to and preparing your exit door for the future.

The thing is markdown is portable by itself. Yes the `file://`-style links make the notes moveable between sub-folders but won't be opened in some markdown editors. Just replace `file://` with your note folder path and any markdown editor will open them. I use my QON notes with Epsilon notes on Android with the above as auto substitution. Make this single replacement action for all the notes and they are almost 100% portable as long as you stay with markdown. Pass them all through pandoc, and they are html/docx/pdf/latex... anything you want with a single command with all the images in-place. That's what differs markdown and tricky json's. Even html is less portable to me. 

The only things that are hardly portable in QON are tags and links to other notes. That's why I ceased using them. I can export them, but there's no standard syntax for that.

**Comment by little-curiosity** [comment]
Thanks for all your comments and input. That't one of the thing that I like about QON with its very active development from @pbek and the communities behind. I think for now I will store the related non-text files in the same folder as the corresponding notes and write a link myself pointing to them. A bit of work but it seems to work for me. Now I need to convert all the web-clip HTML files to markdown. I still wish if I can somehow highlight notes like the way I want, but probably I can convert the web-clips to PDF files and use the native highlighting of PDF readers. Thanks all again.
