### ISSUE TITLE
Suggestions for future features

### ISSUE THREAD

**Issue by jkathir** [pbek/QOwnNotes#699]

**Comment by pbek** [comment]
Thank you for your suggestions. Any volunteers? :)

> tags

there are tags, did you miss a special feature?

> web clipper

you can paste html from the clipboard as markdown

> import

the notes are already plain text-files :)

**Comment by jkathir** [comment]
Thanks for the comments and see whether you can take into consideration and incorporate the other features..

**Comment by pbek** [comment]
I assume even the research what the actual feature requests are will take quite a while...

**Comment by bepolymathe** [comment]
Hi @jkathir 

Can you be more precise for web clipper ? For firefox you have savetotxt to keep only text... for example...

**Comment by Maboroshy** [comment]
Inbox script will soon get an update and start converting saved .htm files to notes. All the code works, just need little more time for script settings and descriptions. 
My clipper-like thing will follow later. But it's quite geeky, and I'm yet to make it work on anything other than Linux.

**Comment by jkathir** [comment]
web clipper is less priority as it is reaping the page via link. some of the items are very useful like google like search, facility to search huge documents, number of hits found before search..

**Comment by Maboroshy** [comment]
Could you explain a bit what you into "reaping the page via link".

**Comment by jkathir** [comment]
web clipper, is an editor that saves a web page locally and displays it. It’s quite useful for downloading content for archival purposes – really invaluable for all note taking needs! The bonus is that the entire web page is saved locally to the note’s attachment folder.

**Comment by Maboroshy** [comment]
Saving web page to attachment is good idea. Maybe I'll implement that to my script.

**Comment by bepolymathe** [comment]
That's will be great... !

**Comment by Maboroshy** [comment]
Not sure yet. My code saves all the images web page has to "media", it also deletes all the rest web page resources, that are useless for a markdown note. 

So it should either copy whole saved web page with resources to "attachments", duplicating the images, or link images to "attachments" instead of "media". 

The web page to note conversion works good only with "distilled" pages, that I save from browser's "reader mode". This mode, at least at Firefox, also puts the link to original page to the first line. So maybe that's enough to find the original page when it's needed.

**Comment by bepolymathe** [comment]
Hi @Maboroshy ,

This is already doing the job well! Personally, I prefer that all the data of the captured from the webpage is in "attachment" rather than "media" ... but that's my point of view.
If you want, I can do a test with the reader mode of Vivaldi which is "chromium like" ...

**Comment by Maboroshy** [comment]
I've uploaded new version of "Inbox" script to the repository. It can work folder-wide and converts saved web pages now. They're some example workflows in description.

**Comment by Maboroshy** [comment]
I've tried this Collatenotes app. Quite good peace of software. 

I've tried it's web clipper, it just saves a web locally. Doesn't simplify it's formatting, doesn't allow text editing or highlighting. Plain dump any browser can do. Since the app runs in Electron, it actually is the browser.  
I think mine is better. :sunglasses: Especially when I'll add inotify and clipboard support.

I liked it's outline-style notes. Maybe I could do something like that in QON. Looks like I'll have to take #672 after all. 

The thing I like about this app and would be good to have in QON is card-like note list. Also I liked that note metadata is stored in note text in YAML-style format. Looks like it parses it. Would be interesting to see how it'd handle 1000 notes. But, since it's Electron based, such parsing may not be the bottle-neck.

The C++ speed of QON leaves all these JavaScript note apps far behind. It's 170 mb installed. Interesting, how many bundled Chrome browsers I'd have on my disk if I was prone to use that type of apps.

**Comment by hackjutsu** [comment]
Seriously? I just came across this post and realized one of my project received an almost identical  feature request. 

A later search astonishes me, quite a few note taking GitHub projects has received same issue from the same user.

**A few examples**
https://github.com/connors/photon/issues/140
https://github.com/tomboy-notes/tomboy/issues/64
https://github.com/JHierrot/openprodoc/issues/1
https://github.com/bevuta/pepa/issues/12
https://github.com/GeniusWiki/GeniusWiki/issues/3
https://github.com/pbek/QOwnNotes/issues/699
https://github.com/sismics/docs/issues/132
https://github.com/Laverna/laverna/issues/816

What surprises me is the issue on [photon](https://github.com/connors/photon). This is a UI framework which has nothing to do with note taking, but still be asked for these feature.

Therefore, I think this is a potential spamming.
