### ISSUE TITLE
Push to git after a number of commits

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#744]
#### Feature request: 

Push to git after a number of commits. If anything goes wrong, the process stops until the application is restarted. The user gets a message and needs to solve everything manually.

I looked through the hooks, but there is no post GIT commit hook, right? 

Is pushing something you are inclined to add to the main application, or do you rather see this in a script? In case of the latter, what hook do you suggest to use?

**Comment by pbek** [comment]
I never did a `git push` because an external repository needs to be in place and conflict management can not be done automatically. But you could use a timer, like in <https://github.com/pbek/QOwnNotes/blob/develop/doc/scripting/example.qml> to do that push every x seconds.

Does that answer your question?

**Comment by sanderboom** [comment]
Every x seconds is not optimal, but doable I think. I'll experiment with creating a script for it. Thanks.

**Comment by pbek** [comment]
If you come up with a great solution please consider doing a pull request to <https://github.com/qownnotes/scripts>!

**Comment by pbek** [comment]
@sanderboom, maybe you want to try https://github.com/muesli/gitomatic/
