### ISSUE TITLE
What might cause a note to be deleted accidentally?

### ISSUE THREAD

**Issue by polarathene** [pbek/QOwnNotes#924]
I was after a note that I made around Jan 2018, and continued to update over several weeks. I made a 2nd related note but it seems I cannot find the original note with all that research I had written to it... It might have been that I later decided to rename the note or copy/paste it's contents into the 2nd related note... however if I did that data is no longer there.

I'm not sure if I lost any other notes, there has been times I thought I had written a note on something but can't seem to locate it. The notes storage doesn't have the file name for the original note there, so it's definitely gone. I'm not sure if it could have been a rare bug in QOwnNotes, a user error(although deleting notes seems to come with confirmation dialog in my experience) or if it's somehow related to a filesystem bug(maybe fsck removed it during boot if the data had become corrupt? I am using XFS).

Granted I should have some proper backup in place to avoid this, just curious how this happened as I've been trusting QOwnNotes to manage/store my research. Is there a chance that QOwnNotes was doing something when a powercut happens? There has been about two this year so far.

**Comment by pbek** [comment]
Do you have some File versioning via git in qownnotes in place or do you
sync to a sync service to get old versions of your files? There is no way
to see what's happened back then otherwise. 😑

On 27 May 2018 07:55, "Brennan Kinney" <notifications@github.com> wrote:

I was after a note that I made around Jan 2018, and continued to update
over several weeks. I made a 2nd related note but it seems I cannot find
the original note with all that research I had written to it... It might
have been that I later decided to rename the note or copy/paste it's
contents into the 2nd related note... however if I did that data is no
longer there.

I'm not sure if I lost any other notes, there has been times I thought I
had written a note on something but can't seem to locate it. The notes
storage doesn't have the file name for the original note there, so it's
definitely gone. I'm not sure if it could have been a rare bug in
QOwnNotes, a user error(although deleting notes seems to come with
confirmation dialog in my experience) or if it's somehow related to a
filesystem bug(maybe fsck removed it during boot if the data had become
corrupt? I am using XFS).

Granted I should have some proper backup in place to avoid this, just
curious how this happened as I've been trusting QOwnNotes to manage/store
my research. Is there a chance that QOwnNotes was doing something when a
powercut happens? There has been about two this year so far.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pbek/QOwnNotes/issues/924>, or mute the thread

**Comment by polarathene** [comment]
@pbek  Nope, no sync setup, no use of git. My bad for not having backup or sync setup :\ Just surprised how the other notes are fine and that one seems to have vanished, ah well..

**Comment by pbek** [comment]
Best use the git feature.
